const fs = require('fs');
const path = require('path');
function outputProduct(id, name, displayName, slug, category, subcategory, price, unit) {
  const mrp = Math.round(price * 1.23);
  const discount = Math.round((mrp - price) / mrp * 100);
  return {
    id,
    name,
    displayName,
    slug,
    brand: 'IGO Agri TechFarms',
    category,
    subcategory,
    price,
    mrp,
    discount,
    stock: 100,
    images: ['/catalog/nursery-essentials/grow-bag.jpg'],
    description: `${displayName} designed for reliable ${subcategory.toLowerCase()} in agricultural and nursery applications.`,
    composition: 'Durable polypropylene construction with UV stabilization, ideal for nursery, greenhouse and hydroponic use.',
    usage: 'Use in nursery, greenhouse or farm propagation units. Clean and dry before reuse.',
    rating: 4.5,
    reviewCount: 28,
    isIgoOwn: true,
    problemFilter: 'Plant Care',
    tags: [subcategory.replace(/ /g, '-').toLowerCase(), category.replace(/ & /g, '-').replace(/ /g, '-').toLowerCase(), 'nursery', 'agriculture'],
    unit,
    isOrganic: false,
    crops: ['All crops'],
  };
}
function format(obj) {
  const lines = ['  {'];
  Object.entries(obj).forEach(([key, value]) => {
    if (typeof value === 'string') {
      lines.push(`    ${key}: '${value.replace(/'/g, "\\'")}',`);
    } else if (typeof value === 'boolean') {
      lines.push(`    ${key}: ${value},`);
    } else if (typeof value === 'number') {
      lines.push(`    ${key}: ${value},`);
    } else if (Array.isArray(value)) {
      const arr = value.map(v => `'${v.replace(/'/g, "\\'")}'`).join(', ');
      lines.push(`    ${key}: [${arr}],`);
    } else {
      lines.push(`    ${key}: ${JSON.stringify(value)},`);
    }
  });
  lines.push('  },');
  return lines.join('\n');
}
const items = [
  ['pdf-gm-001','Soil Block Maker – 40 mm','Soil Block Maker 40mm','germination-media-block-40mm','Germination Media','Soil Block Maker',60,'1 Piece'],
  ['pdf-gm-002','Soil Block Maker – 50 mm','Soil Block Maker 50mm','germination-media-block-50mm','Germination Media','Soil Block Maker',75,'1 Piece'],
  ['pdf-gm-003','Soil Block Maker – 60 mm','Soil Block Maker 60mm','germination-media-block-60mm','Germination Media','Soil Block Maker',95,'1 Piece'],
  ['pdf-gm-004','Soil Block Maker – 80 mm','Soil Block Maker 80mm','germination-media-block-80mm','Germination Media','Soil Block Maker',120,'1 Piece'],
  ['pdf-gm-005','Seedling Tray 72 Cells','Seedling Tray 72 Cells','seedling-tray-72-cells','Germination Media','Seedling Tray',85,'1 Piece'],
  ['pdf-gm-006','Seedling Tray 128 Cells','Seedling Tray 128 Cells','seedling-tray-128-cells','Germination Media','Seedling Tray',95,'1 Piece'],
  ['pdf-gm-007','Seedling Tray 200 Cells','Seedling Tray 200 Cells','seedling-tray-200-cells','Germination Media','Seedling Tray',140,'1 Piece'],
  ['pdf-gm-008','Nursery Tray 18 Cells','Nursery Tray 18 Cells','nursery-tray-18-cells','Germination Media','Nursery Tray',55,'1 Piece'],
  ['pdf-gm-009','Mushroom Spawn Tray','Mushroom Spawn Tray','mushroom-spawn-tray','Germination Media','Spawn Tray',80,'1 Piece'],
  ['pdf-gm-010','Root Trainer Tray','Root Trainer Tray','root-trainer-tray','Germination Media','Root Trainer',98,'1 Piece'],
  ['pdf-gm-011','Sowing Tray Without Holes','Sowing Tray Without Holes','sowing-tray-without-holes','Germination Media','Sowing Tray',52,'1 Piece'],
  ['pdf-gm-012','Sowing Tray With Holes','Sowing Tray With Holes','sowing-tray-with-holes','Germination Media','Sowing Tray',62,'1 Piece'],
  ['pdf-gm-013','Tray with Transparent Lid 102x53','Tray with Transparent Lid 102x53','tray-transparent-lid-102x53','Germination Media','Seedling Tray',125,'1 Piece'],
  ['pdf-gm-014','Tray with Transparent Lid 104x78','Tray with Transparent Lid 104x78','tray-transparent-lid-104x78','Germination Media','Seedling Tray',155,'1 Piece'],
  ['pdf-ps-001','Bamboo Sticks (Pack of 50)','Bamboo Sticks Pack','bamboo-sticks-pack-50','Plant Support Materials','Bamboo Stick',130,'Pack of 50'],
  ['pdf-ps-002','Start Stick 8 Inch (100 pcs)','Start Stick 8 Inch','start-stick-8inch-100pcs','Plant Support Materials','Start Stick',125,'Pack of 100'],
  ['pdf-ps-003','Start Stick 12 Inch (100 pcs)','Start Stick 12 Inch','start-stick-12inch-100pcs','Plant Support Materials','Start Stick',155,'Pack of 100'],
  ['pdf-ps-004','Start Stick 16 Inch (100 pcs)','Start Stick 16 Inch','start-stick-16inch-100pcs','Plant Support Materials','Start Stick',190,'Pack of 100'],
  ['pdf-ps-005','Lashing Twine 100m','Lashing Twine 100m','lashing-twine-100m','Plant Support Materials','Twine',99,'100 m Roll'],
  ['pdf-ps-006','Soft Plant Tie 60m','Soft Plant Tie 60m','soft-plant-tie-60m','Plant Support Materials','Plant Tie',115,'60 m Roll'],
  ['pdf-ps-007','Plant Support Ring 8 Inch','Plant Support Ring 8 Inch','plant-support-ring-8inch','Plant Support Materials','Support Ring',75,'1 Piece'],
  ['pdf-ps-008','Plastic Coated Plant Support Wire 1kg','Support Wire 1kg','plant-support-wire-1kg','Plant Support Materials','Support Wire',245,'1 kg Coil'],
  ['pdf-ps-009','Plant Support Clip 100 pcs','Plant Support Clip 100 pcs','plant-support-clip-100pcs','Plant Support Materials','Support Clip',180,'Pack of 100'],
  ['pdf-ps-010','Grower Net 5x5 ft','Grower Net 5x5 ft','grower-net-5x5','Plant Support Materials','Net',220,'1 Piece'],
  ['pdf-ps-011','Grower Net 6x6 ft','Grower Net 6x6 ft','grower-net-6x6','Plant Support Materials','Net',245,'1 Piece'],
  ['pdf-ps-012','Net Stake Pack','Net Stake Pack','net-stake-pack','Plant Support Materials','Stake Pack',155,'Pack of 20'],
  ['pdf-ps-013','Cage Support 3 Tier','Cage Support 3 Tier','cage-support-3tier','Plant Support Materials','Cage Support',420,'1 Piece'],
  ['pdf-ps-014','Trellis Mesh 1m x 50m','Trellis Mesh 1m x 50m','trellis-mesh-1x50m','Plant Support Materials','Trellis Mesh',760,'1 Roll'],
  ['pdf-ps-015','Trellis Mesh 2m x 50m','Trellis Mesh 2m x 50m','trellis-mesh-2x50m','Plant Support Materials','Trellis Mesh',1250,'1 Roll'],
  ['pdf-ps-016','Basket Support 12 Inch','Basket Support 12 Inch','basket-support-12inch','Plant Support Materials','Basket Support',165,'1 Piece'],
  ['pdf-ps-017','Hanging Basket Chain Set','Hanging Basket Chain Set','hanging-basket-chain-set','Plant Support Materials','Hanging Chain',210,'Set of 3'],
  ['pdf-ps-018','Coconut Coir Rope 250m','Coconut Coir Rope 250m','coconut-coir-rope-250m','Plant Support Materials','Coir Rope',325,'250 m Roll'],
  ['pdf-ps-019','Palm Rope 100m','Palm Rope 100m','palm-rope-100m','Plant Support Materials','Palm Rope',138,'100 m Roll'],
  ['pdf-ps-020','Jute Twine 200m','Jute Twine 200m','jute-twine-200m','Plant Support Materials','Jute Twine',119,'200 m Roll'],
  ['pdf-ps-021','Heat Shrink Tape 10m','Heat Shrink Tape 10m','heat-shrink-tape-10m','Plant Support Materials','Heat Shrink Tape',145,'10 m Roll'],
  ['pdf-ps-022','WaterProof Graft Tape 30m','WaterProof Graft Tape 30m','waterproof-graft-tape-30m','Plant Support Materials','Graft Tape',158,'30 m Roll'],
  ['pdf-ps-023','Horticulture Twine 120m','Horticulture Twine 120m','horticulture-twine-120m','Plant Support Materials','Plant Twine',102,'120 m Roll'],
  ['pdf-ps-024','Drip Line Holder','Drip Line Holder','drip-line-holder','Plant Support Materials','Line Holder',95,'1 Pack'],
  ['pdf-ps-025','Garden Stake 2ft','Garden Stake 2ft','garden-stake-2ft','Plant Support Materials','Stake',84,'1 Piece'],
  ['pdf-ps-026','Garden Stake 3ft','Garden Stake 3ft','garden-stake-3ft','Plant Support Materials','Stake',96,'1 Piece'],
  ['pdf-ps-027','Garden Stake 4ft','Garden Stake 4ft','garden-stake-4ft','Plant Support Materials','Stake',125,'1 Piece'],
  ['pdf-ps-028','Tree Support Brace','Tree Support Brace','tree-support-brace','Plant Support Materials','Support Brace',295,'1 Piece'],
  ['pdf-ps-029','Propagation Label Set 100','Propagation Label Set 100','propagation-label-set-100','Plant Support Materials','Label Set',89,'Pack of 100'],
  ['pdf-ps-030','Plant Marker Board','Plant Marker Board','plant-marker-board','Plant Support Materials','Marker Board',210,'1 Piece'],
  ['pdf-ps-031','Plant Support Clamp 50','Plant Support Clamp 50','plant-support-clamp-50','Plant Support Materials','Support Clamp',255,'Pack of 50'],
  ['pdf-ps-032','Mesh Sleeve 1m','Mesh Sleeve 1m','mesh-sleeve-1m','Plant Support Materials','Mesh Sleeve',135,'1 Piece'],
  ['pdf-ps-033','Shade Net Clip 25','Shade Net Clip 25','shade-net-clip-25','Plant Support Materials','Shade Net Clip',79,'Pack of 25'],
  ['pdf-ps-034','Tomato Cage 12x12','Tomato Cage 12x12','tomato-cage-12x12','Plant Support Materials','Tomato Cage',425,'1 Piece'],
  ['pdf-at-001','Seed Tray 24 Cells','Seed Tray 24 Cells','seed-tray-24-cells','Agriculture Trays','Seed Tray',72,'1 Piece'],
  ['pdf-at-002','Seed Tray 32 Cells','Seed Tray 32 Cells','seed-tray-32-cells','Agriculture Trays','Seed Tray',82,'1 Piece'],
  ['pdf-at-003','Seed Tray 48 Cells','Seed Tray 48 Cells','seed-tray-48-cells','Agriculture Trays','Seed Tray',96,'1 Piece'],
  ['pdf-at-004','Raised Bed Tray 60x40','Raised Bed Tray 60x40','raised-bed-tray-60x40','Agriculture Trays','Raised Bed Tray',160,'1 Piece'],
  ['pdf-at-005','Raised Bed Tray 80x50','Raised Bed Tray 80x50','raised-bed-tray-80x50','Agriculture Trays','Raised Bed Tray',220,'1 Piece'],
  ['pdf-at-006','Mobile Nursery Tray','Mobile Nursery Tray','mobile-nursery-tray','Agriculture Trays','Mobile Tray',320,'1 Piece'],
  ['pdf-at-007','Germination Tray 96 Cells','Germination Tray 96 Cells','germination-tray-96-cells','Agriculture Trays','Germination Tray',118,'1 Piece'],
  ['pdf-at-008','Transplant Tray 30 Cells','Transplant Tray 30 Cells','transplant-tray-30-cells','Agriculture Trays','Transplant Tray',110,'1 Piece'],
  ['pdf-at-009','Plug Tray 128 Cells','Plug Tray 128 Cells','plug-tray-128-cells','Agriculture Trays','Plug Tray',132,'1 Piece'],
  ['pdf-at-010','Mini Tray 12 Cells','Mini Tray 12 Cells','mini-tray-12-cells','Agriculture Trays','Mini Tray',55,'1 Piece'],
  ['pdf-at-011','Microgreen Tray','Microgreen Tray','microgreen-tray','Agriculture Trays','Microgreen Tray',85,'1 Piece'],
  ['pdf-at-012','Hydroponic Tray 4ft','Hydroponic Tray 4ft','hydroponic-tray-4ft','Agriculture Trays','Hydroponic Tray',420,'1 Piece'],
  ['pdf-at-013','Hydroponic Tray 8ft','Hydroponic Tray 8ft','hydroponic-tray-8ft','Agriculture Trays','Hydroponic Tray',780,'1 Piece'],
  ['pdf-at-014','Seedling Plug Tray 40mm','Seedling Plug Tray 40mm','seedling-plug-tray-40mm','Agriculture Trays','Plug Tray',145,'1 Piece'],
  ['pdf-at-015','Multipurpose Tray','Multipurpose Tray','multipurpose-tray','Agriculture Trays','Multipurpose Tray',98,'1 Piece'],
  ['pdf-at-016','Stackable Tray Set 5','Stackable Tray Set 5','stackable-tray-set-5','Agriculture Trays','Stackable Tray',420,'Set of 5'],
  ['pdf-at-017','Tray Divider Kit','Tray Divider Kit','tray-divider-kit','Agriculture Trays','Tray Divider',115,'1 Kit'],
  ['pdf-tr-001','Plastic Reservoir Tank 100 L','Plastic Reservoir Tank 100 L','plastic-reservoir-tank-100l','Tanks & Reservoirs','Reservoir Tank',980,'100 L'],
  ['pdf-tr-002','Plastic Reservoir Tank 200 L','Plastic Reservoir Tank 200 L','plastic-reservoir-tank-200l','Tanks & Reservoirs','Reservoir Tank',1580,'200 L'],
  ['pdf-tr-003','Plastic Reservoir Tank 500 L','Plastic Reservoir Tank 500 L','plastic-reservoir-tank-500l','Tanks & Reservoirs','Reservoir Tank',3290,'500 L'],
  ['pdf-tr-004','HDPE Tank 1000 L','HDPE Tank 1000 L','hdpe-tank-1000l','Tanks & Reservoirs','HDPE Tank',7200,'1000 L'],
  ['pdf-tr-005','HDPE Tank 2000 L','HDPE Tank 2000 L','hdpe-tank-2000l','Tanks & Reservoirs','HDPE Tank',12950,'2000 L'],
  ['pdf-tr-006','Water Reservoir 50 L','Water Reservoir 50 L','water-reservoir-50l','Tanks & Reservoirs','Water Reservoir',730,'50 L'],
  ['pdf-tr-007','Fertilizer Tank 75 L','Fertilizer Tank 75 L','fertilizer-tank-75l','Tanks & Reservoirs','Fertilizer Tank',890,'75 L'],
  ['pdf-tr-008','Poly Tank 120 L','Poly Tank 120 L','poly-tank-120l','Tanks & Reservoirs','Poly Tank',1020,'120 L'],
  ['pdf-tr-009','Misting Reservoir 30 L','Misting Reservoir 30 L','misting-reservoir-30l','Tanks & Reservoirs','Misting Reservoir',640,'30 L'],
  ['pdf-tr-010','Storage Container 25 L','Storage Container 25 L','storage-container-25l','Tanks & Reservoirs','Storage Container',520,'25 L'],
  ['pdf-ir-001','Garden Hose 2 Ply 25mm','Garden Hose 2 Ply 25mm','garden-hose-2ply-25mm','Pumps & Irrigation','Garden Hose',210,'25 mm'],
  ['pdf-ir-002','Garden Hose 2 Ply 32mm','Garden Hose 2 Ply 32mm','garden-hose-2ply-32mm','Pumps & Irrigation','Garden Hose',320,'32 mm'],
  ['pdf-ir-003','Color Garden Hose 25mm','Color Garden Hose 25mm','color-garden-hose-25mm','Pumps & Irrigation','Garden Hose',255,'25 mm'],
  ['pdf-ir-004','Color Garden Hose 32mm','Color Garden Hose 32mm','color-garden-hose-32mm','Pumps & Irrigation','Garden Hose',365,'32 mm'],
  ['pdf-ir-005','Conductive PVC Pipe 20mm','Conductive PVC Pipe 20mm','conductive-pvc-pipe-20mm','Pumps & Irrigation','PVC Pipe',85,'20 mm/meter'],
  ['pdf-ir-006','Conductive PVC Pipe 25mm','Conductive PVC Pipe 25mm','conductive-pvc-pipe-25mm','Pumps & Irrigation','PVC Pipe',98,'25 mm/meter'],
  ['pdf-ir-007','Conductive PVC Pipe 32mm','Conductive PVC Pipe 32mm','conductive-pvc-pipe-32mm','Pumps & Irrigation','PVC Pipe',125,'32 mm/meter'],
  ['pdf-ir-008','Agriculture Pipe 20mm','Agriculture Pipe 20mm','agriculture-pipe-20mm','Pumps & Irrigation','Agriculture Pipe',90,'20 mm/meter'],
  ['pdf-ir-009','Agriculture Pipe 25mm','Agriculture Pipe 25mm','agriculture-pipe-25mm','Pumps & Irrigation','Agriculture Pipe',108,'25 mm/meter'],
  ['pdf-ir-010','Agriculture Pipe 32mm','Agriculture Pipe 32mm','agriculture-pipe-32mm','Pumps & Irrigation','Agriculture Pipe',138,'32 mm/meter'],
  ['pdf-ir-011','HDPE Tube 16mm','HDPE Tube 16mm','hdpe-tube-16mm','Pumps & Irrigation','HDPE Tube',92,'16 mm/meter'],
  ['pdf-ir-012','HDPE Tube 20mm','HDPE Tube 20mm','hdpe-tube-20mm','Pumps & Irrigation','HDPE Tube',120,'20 mm/meter'],
  ['pdf-ir-013','HDPE Tube 25mm','HDPE Tube 25mm','hdpe-tube-25mm','Pumps & Irrigation','HDPE Tube',145,'25 mm/meter'],
  ['pdf-ir-014','HDPE Tube 32mm','HDPE Tube 32mm','hdpe-tube-32mm','Pumps & Irrigation','HDPE Tube',198,'32 mm/meter'],
  ['pdf-ir-015','PVC Main Pipe 40mm','PVC Main Pipe 40mm','pvc-main-pipe-40mm','Pumps & Irrigation','PVC Main Pipe',225,'40 mm/meter'],
  ['pdf-ir-016','PVC Main Pipe 50mm','PVC Main Pipe 50mm','pvc-main-pipe-50mm','Pumps & Irrigation','PVC Main Pipe',265,'50 mm/meter'],
  ['pdf-ir-017','PVC Main Pipe 63mm','PVC Main Pipe 63mm','pvc-main-pipe-63mm','Pumps & Irrigation','PVC Main Pipe',320,'63 mm/meter'],
  ['pdf-ir-018','Low Flow Drip Irrigation Pipe 16mm','Low Flow Drip Irrigation Pipe 16mm','low-flow-drip-irrigation-pipe-16mm','Pumps & Irrigation','Drip Pipe',92,'16 mm/meter'],
  ['pdf-ir-019','Low Flow Drip Irrigation Pipe 20mm','Low Flow Drip Irrigation Pipe 20mm','low-flow-drip-irrigation-pipe-20mm','Pumps & Irrigation','Drip Pipe',118,'20 mm/meter'],
  ['pdf-ir-020','Low Flow Drip Irrigation Pipe 25mm','Low Flow Drip Irrigation Pipe 25mm','low-flow-drip-irrigation-pipe-25mm','Pumps & Irrigation','Drip Pipe',145,'25 mm/meter'],
  ['pdf-ir-021','Sprinkler Pipe 25mm','Sprinkler Pipe 25mm','sprinkler-pipe-25mm','Pumps & Irrigation','Sprinkler Pipe',170,'25 mm/meter'],
  ['pdf-ir-022','Sprinkler Pipe 32mm','Sprinkler Pipe 32mm','sprinkler-pipe-32mm','Pumps & Irrigation','Sprinkler Pipe',205,'32 mm/meter'],
  ['pdf-ir-023','Subsurface Drip Tape 20mm','Subsurface Drip Tape 20mm','subsurface-drip-tape-20mm','Pumps & Irrigation','Drip Tape',115,'20 mm/meter'],
  ['pdf-ir-024','Subsurface Drip Tape 25mm','Subsurface Drip Tape 25mm','subsurface-drip-tape-25mm','Pumps & Irrigation','Drip Tape',145,'25 mm/meter'],
  ['pdf-ir-025','Micro Sprinkler Set 10','Micro Sprinkler Set 10','micro-sprinkler-set-10','Pumps & Irrigation','Micro Sprinkler',1320,'Set of 10'],
  ['pdf-ir-026','Sprinkler Nozzle Pack 10','Sprinkler Nozzle Pack 10','sprinkler-nozzle-pack-10','Pumps & Irrigation','Nozzle Pack',540,'Pack of 10'],
  ['pdf-ir-027','Long Drain Pipe 50mm','Long Drain Pipe 50mm','long-drain-pipe-50mm','Pumps & Irrigation','Drain Pipe',380,'50 mm/meter'],
  ['pdf-ir-028','Lawn Sprinkler System','Lawn Sprinkler System','lawn-sprinkler-system','Pumps & Irrigation','Sprinkler Kit',1450,'1 Set'],
  ['pdf-ir-029','Garden Irrigation Kit','Garden Irrigation Kit','garden-irrigation-kit','Pumps & Irrigation','Irrigation Kit',950,'1 Kit'],
  ['pdf-ir-030','Water Gun 1.5 Inch','Water Gun 1.5 Inch','water-gun-1-5-inch','Pumps & Irrigation','Water Gun',390,'1 Piece'],
  ['pdf-ir-031','Water Gun 2 Inch','Water Gun 2 Inch','water-gun-2-inch','Pumps & Irrigation','Water Gun',480,'1 Piece'],
  ['pdf-ir-032','Water Spray Gun','Water Spray Gun','water-spray-gun','Pumps & Irrigation','Spray Gun',290,'1 Piece'],
  ['pdf-ir-033','Water Spray Lance','Water Spray Lance','water-spray-lance','Pumps & Irrigation','Spray Lance',525,'1 Piece'],
  ['pdf-ir-034','Water Gun Nozzle Set','Water Gun Nozzle Set','water-gun-nozzle-set','Pumps & Irrigation','Nozzle Set',245,'Set of 5'],
  ['pdf-ir-035','Portable Pump 0.5 HP','Portable Pump 0.5 HP','portable-pump-0-5-hp','Pumps & Irrigation','Portable Pump',3720,'0.5 HP'],
  ['pdf-ir-036','Portable Pump 1 HP','Portable Pump 1 HP','portable-pump-1-hp','Pumps & Irrigation','Portable Pump',5620,'1 HP'],
  ['pdf-ir-037','Submersible Pump 0.75 HP','Submersible Pump 0.75 HP','submersible-pump-0-75-hp','Pumps & Irrigation','Submersible Pump',7680,'0.75 HP'],
  ['pdf-ir-038','Drip Irrigation Valve','Drip Irrigation Valve','drip-irrigation-valve','Pumps & Irrigation','Valve',175,'1 Piece'],
  ['pdf-ir-039','Solenoid Valve 24V','Solenoid Valve 24V','solenoid-valve-24v','Pumps & Irrigation','Solenoid Valve',320,'1 Piece'],
];
const text = items.map(item => format(outputProduct(...item))).join('\n');
fs.writeFileSync(path.join(process.cwd(), 'new_products_block.txt'), text);
console.log('created');
