import { Category, Product } from './types';

export const MARKETPLACE_EXPANSION_CATEGORIES: Category[] = [
  { id: 'crop-protection', name: 'Crop Protection', slug: 'crop-protection', icon: 'ShieldAlert', productCount: 18 },
  { id: 'growth-regulators', name: 'Growth Regulators', slug: 'growth-regulators', icon: 'TrendingUp', productCount: 10 },
  { id: 'gardening-products', name: 'Gardening Products', slug: 'gardening-products', icon: 'Flower2', productCount: 12 },
  { id: 'cattle-bird-care', name: 'Cattle & Bird Care', slug: 'cattle-bird-care', icon: 'Beef', productCount: 10 },
  { id: 'bulk-agri-supplies', name: 'Bulk Agri Supplies', slug: 'bulk-agri-supplies', icon: 'Package', productCount: 12 },
  { id: 'agri-offers-combos', name: 'Agri Offers & Combos', slug: 'agri-offers-combos', icon: 'Percent', productCount: 8 },
];

type Spec = {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  mrp: number;
  unit: string;
  image: string;
  problemFilter: string;
  crops: string[];
  tags: string[];
  isOrganic?: boolean;
  composition: string;
  usage: string;
};

const specs: Spec[] = [
  {
    id: 'mp-cp-001',
    name: 'Chlorantraniliprole 18.5% SC Insecticide',
    brand: 'FMC',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 129,
    mrp: 220,
    unit: '10 ml bottle',
    image: '/catalog/crop-care/liquid/Liquid%20NPK%2020-20-20.png',
    problemFilter: 'Pest Control',
    crops: ['Paddy', 'Tomato', 'Chilli', 'Cotton'],
    tags: ['insecticide', 'borer-control', 'crop-protection', 'high-demand'],
    composition: 'Chlorantraniliprole 18.5% SC broad-spectrum insecticide formulation.',
    usage: 'Apply only as per label recommendation through foliar spray. Use gloves, mask and clean water while mixing.',
  },
  {
    id: 'mp-cp-002',
    name: 'Tebuconazole 50% + Trifloxystrobin 25% WG Fungicide',
    brand: 'Bayer',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 156,
    mrp: 180,
    unit: '10 g pack',
    image: '/catalog/crop-care/powder/Copper%20Sulphate.jpeg',
    problemFilter: 'Disease Control',
    crops: ['Paddy', 'Grapes', 'Mango', 'Vegetables'],
    tags: ['fungicide', 'leaf-spot', 'powdery-mildew', 'crop-protection'],
    composition: 'Systemic dual-action fungicide with tebuconazole and trifloxystrobin active ingredients.',
    usage: 'Spray at first disease appearance and repeat based on crop advisory. Avoid spraying during peak sunlight.',
  },
  {
    id: 'mp-cp-003',
    name: 'Broflanilide 300 g/L SC Insecticide',
    brand: 'BASF',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 613,
    mrp: 731,
    unit: '8.5 ml bottle',
    image: '/catalog/organic-bio-inputs/bio-fertilizer.webp',
    problemFilter: 'Pest Control',
    crops: ['Brinjal', 'Tomato', 'Chilli', 'Okra'],
    tags: ['insecticide', 'caterpillar-control', 'fruit-borer', 'premium'],
    composition: 'Broflanilide 300 g/L suspension concentrate insecticide.',
    usage: 'Use for resistant chewing pests under agronomist guidance. Follow label harvest interval strictly.',
  },
  {
    id: 'mp-cp-004',
    name: 'Glyphosate 41% SL Non-Selective Herbicide',
    brand: 'Bayer',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 158,
    mrp: 225,
    unit: '250 ml bottle',
    image: '/catalog/organic-bio-inputs/neem-leaves.webp',
    problemFilter: 'Pest Control',
    crops: ['Orchards', 'Plantation Crops', 'Farm Bunds'],
    tags: ['herbicide', 'weed-control', 'non-selective', 'orchard'],
    composition: 'Glyphosate 41% SL soluble liquid herbicide.',
    usage: 'Apply only on unwanted weeds. Do not spray on standing crop foliage or green stems.',
  },
  {
    id: 'mp-cp-005',
    name: 'Beta-Cyfluthrin + Imidacloprid OD Insecticide',
    brand: 'Bayer',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 377,
    mrp: 450,
    unit: '100 ml bottle',
    image: '/catalog/crop-care/powder/Humic%20Acid%20Powder.jpeg',
    problemFilter: 'Pest Control',
    crops: ['Cotton', 'Chilli', 'Vegetables'],
    tags: ['sucking-pest', 'insecticide', 'thrips', 'aphids'],
    composition: 'Combination insecticide containing beta-cyfluthrin and imidacloprid OD formulation.',
    usage: 'Spray uniformly when sucking pest population crosses threshold. Rotate chemistry to manage resistance.',
  },
  {
    id: 'mp-cp-006',
    name: 'Thiamethoxam 30% FS Seed Treatment Insecticide',
    brand: 'Katyayani',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 389,
    mrp: 640,
    unit: '100 ml bottle',
    image: '/catalog/crop-care/Field%20Seeds/Paddy.webp',
    problemFilter: 'Pest Control',
    crops: ['Cotton', 'Maize', 'Soybean', 'Groundnut'],
    tags: ['seed-treatment', 'thiamethoxam', 'early-pest-control'],
    composition: 'Thiamethoxam 30% FS seed treatment formulation.',
    usage: 'Treat seed before sowing as per crop label dose. Dry treated seed in shade before planting.',
  },
  {
    id: 'mp-cp-007',
    name: 'Spinosad 45% SC Bio-Insecticide',
    brand: 'Dhanuka',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 465,
    mrp: 620,
    unit: '75 ml bottle',
    image: '/catalog/organic-bio-inputs/neem-leaves.webp',
    problemFilter: 'Pest Control',
    crops: ['Chilli', 'Cotton', 'Tomato', 'Cabbage'],
    tags: ['bio-pesticide', 'thrips', 'organic-ipm', 'spinosad'],
    isOrganic: true,
    composition: 'Spinosad 45% SC naturally derived insect control formulation.',
    usage: 'Use as part of IPM rotation. Spray during cooler hours for best performance.',
  },
  {
    id: 'mp-cp-008',
    name: 'Copper Oxychloride Contact Fungicide',
    brand: 'Tata Rallis',
    category: 'Crop Protection',
    subcategory: 'Crop Protection',
    price: 280,
    mrp: 360,
    unit: '500 g pack',
    image: '/catalog/crop-care/powder/Copper%20Sulphate.jpeg',
    problemFilter: 'Disease Control',
    crops: ['Mango', 'Grapes', 'Citrus', 'Vegetables'],
    tags: ['fungicide', 'bacterial-blight', 'leaf-spot', 'copper'],
    composition: 'Copper-based contact fungicide for preventive disease protection.',
    usage: 'Mix thoroughly and spray as a protective cover before disease spread. Do not overdose.',
  },
  {
    id: 'mp-gr-001',
    name: 'Fruit & Flowering Booster Plant Growth Regulator',
    brand: 'TAPAS',
    category: 'Growth Regulators',
    subcategory: 'Growth Regulators',
    price: 479,
    mrp: 700,
    unit: '10 ml ampoule',
    image: '/catalog/crop-care/liquid/Amino%20Acid%20Fertilizer.png',
    problemFilter: 'Growth Boosters',
    crops: ['Mango', 'Tomato', 'Chilli', 'Flowers'],
    tags: ['growth-regulator', 'flowering', 'fruit-set', 'booster'],
    composition: 'Concentrated plant growth regulator blend with flowering and fruit-set stimulants.',
    usage: 'Dilute as directed and spray at flowering initiation or fruit-setting stage.',
  },
  {
    id: 'mp-gr-002',
    name: 'Seaweed Extract Liquid Bio-Stimulant',
    brand: 'PI Industries',
    category: 'Growth Regulators',
    subcategory: 'Organic & Bio Inputs',
    price: 358,
    mrp: 390,
    unit: '250 ml bottle',
    image: '/catalog/organic-bio-inputs/bio-fertilizer.webp',
    problemFilter: 'Growth Boosters',
    crops: ['All crops'],
    tags: ['seaweed', 'bio-stimulant', 'root-growth', 'stress-recovery'],
    isOrganic: true,
    composition: 'Ascophyllum nodosum seaweed extract enriched with natural growth compounds.',
    usage: 'Use as foliar spray or drip input during vegetative and stress recovery stages.',
  },
  {
    id: 'mp-gr-003',
    name: 'Humic Acid 98% Water Soluble Flakes',
    brand: 'Katyayani',
    category: 'Growth Regulators',
    subcategory: 'Organic & Bio Inputs',
    price: 760,
    mrp: 1880,
    unit: '1.6 kg pack',
    image: '/catalog/crop-care/liquid/Humic%20Acid.png',
    problemFilter: 'Soil Health',
    crops: ['All crops'],
    tags: ['humic-acid', 'soil-health', 'root-growth', 'organic'],
    isOrganic: true,
    composition: 'High-concentration humic acid flakes with fulvic fractions.',
    usage: 'Apply through drip, soil drench or basal mixing based on soil organic-carbon status.',
  },
  {
    id: 'mp-gr-004',
    name: 'Amino Acid Crop Tonic',
    brand: 'Coromandel',
    category: 'Growth Regulators',
    subcategory: 'Growth Regulators',
    price: 265,
    mrp: 430,
    unit: '100 ml bottle',
    image: '/catalog/crop-care/liquid/Amino%20Acid%20Fertilizer.png',
    problemFilter: 'Growth Boosters',
    crops: ['Vegetables', 'Flowers', 'Fruit Crops'],
    tags: ['amino-acid', 'crop-tonic', 'stress-management'],
    composition: 'Amino acid and vitamin-based foliar crop tonic.',
    usage: 'Spray during vegetative growth, transplant shock or after weather stress.',
  },
  {
    id: 'mp-gd-001',
    name: 'Battery Sprayer Single Motor 12x8',
    brand: 'TAPAS',
    category: 'Gardening Products',
    subcategory: 'Irrigation Systems',
    price: 2599,
    mrp: 4999,
    unit: '1 unit',
    image: '/catalog/nursery-essentials/VIVOSUN%20Battery%20Powered%20Backpack%20Electric.jpg',
    problemFilter: 'Pest Control',
    crops: ['All crops'],
    tags: ['battery-sprayer', 'spray-pump', 'garden', 'farm-tools'],
    composition: 'Rechargeable battery sprayer with tank, lance, hose and nozzle kit.',
    usage: 'Charge fully before use, rinse after spraying and store with tank empty.',
  },
  {
    id: 'mp-gd-002',
    name: 'Silicone Thumb Cutter With Finger Guard',
    brand: 'Radhe',
    category: 'Gardening Products',
    subcategory: 'Nursery & Garden Essentials',
    price: 149,
    mrp: 249,
    unit: 'Pack of 5',
    image: '/catalog/nursery-essentials/plant-cutter.jpg',
    problemFilter: 'Growth Boosters',
    crops: ['Vegetables', 'Flowers', 'Fruit Crops'],
    tags: ['thumb-cutter', 'harvesting-tool', 'gardening'],
    composition: 'Food-safe silicone finger sleeve with stainless cutting blade.',
    usage: 'Use for vegetable, grape and flower plucking. Wash and dry after each use.',
  },
  {
    id: 'mp-gd-003',
    name: 'HDPE Garden Shade Net 50%',
    brand: 'Green Garden',
    category: 'Gardening Products',
    subcategory: 'Nursery & Garden Essentials',
    price: 690,
    mrp: 990,
    unit: '3 m x 5 m',
    image: '/catalog/nursery-essentials/shade-net.jpg',
    problemFilter: 'Growth Boosters',
    crops: ['Nursery Plants', 'Vegetables', 'Flowers'],
    tags: ['shade-net', 'nursery', 'heat-protection', 'gardening'],
    composition: 'UV-stabilized HDPE shade net for nursery and garden protection.',
    usage: 'Install over nursery beds or terrace gardens with firm anchoring on all edges.',
  },
  {
    id: 'mp-gd-004',
    name: 'Coco Peat Grow Media Block',
    brand: 'Farmers Factory',
    category: 'Gardening Products',
    subcategory: 'Grow Media & Substrates',
    price: 185,
    mrp: 240,
    unit: '5 kg block',
    image: '/catalog/nursery-essentials/cocopeat.png',
    problemFilter: 'Soil Health',
    crops: ['Nursery Plants', 'Vegetables', 'Flowers'],
    tags: ['cocopeat', 'grow-media', 'nursery', 'organic'],
    isOrganic: true,
    composition: 'Washed and compressed coconut coir pith grow media.',
    usage: 'Hydrate with clean water, loosen fully and blend with compost before planting.',
  },
  {
    id: 'mp-ab-001',
    name: 'Cattle Mineral Mixture',
    brand: 'IGO Protein Cuts',
    category: 'Animal Husbandry',
    subcategory: 'Animal Husbandry',
    price: 420,
    mrp: 560,
    unit: '5 kg bag',
    image: '/catalog/animal-husbandry/cattle.webp',
    problemFilter: 'Growth Boosters',
    crops: ['Dairy'],
    tags: ['cattle-care', 'mineral-mixture', 'dairy', 'animal-husbandry'],
    composition: 'Balanced macro and trace mineral mixture for cattle supplementation.',
    usage: 'Mix with daily feed as per veterinarian or nutritionist recommendation.',
  },
  {
    id: 'mp-ab-002',
    name: 'Poultry Feed Supplement',
    brand: 'IGO Protein Cuts',
    category: 'Animal Husbandry',
    subcategory: 'Animal Husbandry',
    price: 310,
    mrp: 430,
    unit: '2 kg pouch',
    image: '/catalog/animal-husbandry/poultry.webp',
    problemFilter: 'Growth Boosters',
    crops: ['Poultry'],
    tags: ['poultry', 'feed-supplement', 'bird-care'],
    composition: 'Vitamin, mineral and amino-acid supplement for poultry feed enrichment.',
    usage: 'Blend uniformly with feed and keep drinking water available at all times.',
  },
  {
    id: 'mp-ab-003',
    name: 'Azolla Growing Bed Kit',
    brand: 'Farmers Factory',
    category: 'Animal Husbandry',
    subcategory: 'Animal Husbandry',
    price: 1180,
    mrp: 1600,
    unit: '1 kit',
    image: '/catalog/animal-husbandry/goat-farm.webp',
    problemFilter: 'Growth Boosters',
    crops: ['Dairy', 'Goat', 'Poultry'],
    tags: ['azolla', 'fodder', 'animal-husbandry', 'kit'],
    composition: 'Foldable azolla bed kit with liner and starter guidance.',
    usage: 'Place on level ground, fill with clean water and follow starter culture instructions.',
  },
  {
    id: 'mp-bulk-001',
    name: 'Bulk Vermicompost FPO Pack',
    brand: 'Farmers Factory',
    category: 'Agri Offers & Combos',
    subcategory: 'Organic & Bio Inputs',
    price: 7200,
    mrp: 9000,
    unit: '500 kg lot',
    image: '/catalog/organic-bio-inputs/compost.webp',
    problemFilter: 'Soil Health',
    crops: ['All crops'],
    tags: ['bulk', 'vermicompost', 'fpo', 'organic'],
    isOrganic: true,
    composition: 'Screened vermicompost prepared from decomposed organic biomass.',
    usage: 'Use as basal soil amendment before sowing or transplanting.',
  },
  {
    id: 'mp-bulk-002',
    name: 'Mulching Sheet Roll',
    brand: 'ANIL PACKAGING',
    category: 'Agri Offers & Combos',
    subcategory: 'Nursery & Garden Essentials',
    price: 2330,
    mrp: 2999,
    unit: '20 micron roll',
    image: '/catalog/post-harvest-storage/packing.webp',
    problemFilter: 'Growth Boosters',
    crops: ['Vegetables', 'Melons', 'Flowers'],
    tags: ['mulching', 'weed-control', 'bulk', 'horticulture'],
    composition: 'UV-stabilized agricultural mulching film roll.',
    usage: 'Lay on prepared raised beds before transplanting and secure sides with soil.',
  },
  {
    id: 'mp-bulk-003',
    name: 'Hermetic Grain Storage Bags',
    brand: 'IGO Exports & Imports',
    category: 'Agri Offers & Combos',
    subcategory: 'Post-Harvest & Storage',
    price: 1480,
    mrp: 1900,
    unit: 'Pack of 10',
    image: '/catalog/post-harvest-storage/grain-storage.webp',
    problemFilter: 'Disease Control',
    crops: ['Paddy', 'Maize', 'Millets', 'Pulses'],
    tags: ['storage', 'post-harvest', 'grain-bag', 'bulk'],
    composition: 'Multi-layer hermetic storage bags for dry grains and pulses.',
    usage: 'Fill only dry produce, remove excess air and seal tightly for storage.',
  },
  {
    id: 'mp-combo-001',
    name: 'Tomato Pest & Flowering Combo',
    brand: 'IGO Precision Farming',
    category: 'Agri Offers & Combos',
    subcategory: 'Agri Offers & Combos',
    price: 493,
    mrp: 1031,
    unit: '1 combo kit',
    image: '/catalog/farmer-factory-vegetables/TomatoCountry.jfif',
    problemFilter: 'Pest Control',
    crops: ['Tomato'],
    tags: ['combo', 'tomato', 'pest-control', 'flowering'],
    composition: 'Curated tomato crop kit with pest control and flowering support inputs.',
    usage: 'Use kit items stage-wise as printed on the IGO crop schedule card.',
  },
  {
    id: 'mp-combo-002',
    name: 'Mango Harvest & Fruit Care Combo',
    brand: 'Farmers Factory',
    category: 'Agri Offers & Combos',
    subcategory: 'Crop Protection',
    price: 899,
    mrp: 1299,
    unit: '1 combo kit',
    image: '/catalog/farmer-factory-fruits/MangoBanganapalli.jfif',
    problemFilter: 'Growth Boosters',
    crops: ['Mango'],
    tags: ['mango', 'fruit-care', 'harvest', 'combo'],
    composition: 'Fruit care combo with growth support, harvesting aid and advisory card.',
    usage: 'Use during fruit-development and harvest period as per included crop schedule.',
  },
];

function slugify(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

export const MARKETPLACE_EXPANSION_PRODUCTS: Product[] = specs.map((item, index) => {
  const discount = Math.max(0, Math.round(((item.mrp - item.price) / item.mrp) * 100));
  return {
    id: item.id,
    name: item.name,
    displayName: item.name,
    slug: slugify(item.name),
    brand: item.brand,
    category: item.category,
    subcategory: item.subcategory,
    price: item.price,
    mrp: item.mrp,
    discount,
    stock: 60 + (index % 9) * 11,
    images: [item.image],
    description: `${item.name} has been added to IGO AgriMart's combined marketplace catalog to cover the high-demand agri-input families seen across leading Indian agri-commerce stores: seeds, crop protection, nutrition, gardening, irrigation, animal care and bulk farm supplies.`,
    composition: item.composition,
    usage: item.usage,
    rating: 4.1 + (index % 8) / 10,
    reviewCount: 35 + (index * 17) % 640,
    isIgoOwn: item.brand.startsWith('IGO') || item.brand === 'Farmers Factory',
    problemFilter: item.problemFilter,
    tags: item.tags,
    unit: item.unit,
    isOrganic: Boolean(item.isOrganic),
    crops: item.crops,
    certifications: [
      {
        name: item.category === 'Crop Protection' ? 'CIB&RC / label compliance required' : 'IGO Quality Checked',
        issuer: 'IGO AgriMart',
        isVerified: true,
      },
    ],
  };
});
