// AUTO-GENERATED from "Polyhouse Costing.pdf" (uploaded by owner).
// Complete polyhouse construction catalog: foundation materials, GI structure
// pipes, covering materials and Jain drip-irrigation components.
// Prices use the PDF selling rate (base rate plus 30 percent margin);
// foundation items (no rate in PDF) use current market rates.
import { Product, Category } from './types';

export const POLYHOUSE_CATEGORIES: Category[] = [
  { id: 'greenhouse-polyhouse', name: 'Greenhouse & Polyhouse', slug: 'greenhouse-polyhouse', icon: 'Home', productCount: 32 }
];

export const POLYHOUSE_PRODUCTS: Product[] = [
  {
    id: 'prod-poly-1',
    slug: 'polyhouse-measuring-tape',
    name: 'Measuring Tape',
    displayName: 'Measuring Tape',
    brand: 'IGO Polyhouse',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Foundation Materials',
    price: 449,
    mrp: 530,
    discount: 15,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=600&q=75&fit=crop'],
    description: 'Measuring Tape (50 m) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 50 m. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'foundation-materials'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-2',
    slug: 'polyhouse-calcium-marking-powder',
    name: 'Calcium Marking Powder',
    displayName: 'Calcium Marking Powder',
    brand: 'IGO Polyhouse',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Foundation Materials',
    price: 199,
    mrp: 235,
    discount: 15,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=600&q=75&fit=crop'],
    description: 'Calcium Marking Powder (5 kg) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 5 kg. Sold per bag.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'foundation-materials'],
    unit: 'per bag',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-3',
    slug: 'polyhouse-marking-nylon-rope',
    name: 'Marking Nylon Rope',
    displayName: 'Marking Nylon Rope',
    brand: 'IGO Polyhouse',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Foundation Materials',
    price: 149,
    mrp: 176,
    discount: 15,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=600&q=75&fit=crop'],
    description: 'Marking Nylon Rope (100 m roll) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 100 m roll. Sold per roll.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'foundation-materials'],
    unit: 'per roll',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-4',
    slug: 'polyhouse-cement',
    name: 'Cement',
    displayName: 'Cement',
    brand: 'IGO Polyhouse',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Foundation Materials',
    price: 419,
    mrp: 494,
    discount: 15,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=600&q=75&fit=crop'],
    description: 'Cement (50 kg) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 50 kg. Sold per bag.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'foundation-materials'],
    unit: 'per bag',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-5',
    slug: 'polyhouse-aggregate-blue-metal',
    name: 'Aggregate (Blue Metal)',
    displayName: 'Aggregate (Blue Metal)',
    brand: 'IGO Polyhouse',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Foundation Materials',
    price: 65,
    mrp: 77,
    discount: 16,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=600&q=75&fit=crop'],
    description: 'Aggregate (Blue Metal) (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per cft.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'foundation-materials'],
    unit: 'per cft',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-6',
    slug: 'polyhouse-gi-foundation-pipe',
    name: 'GI Foundation Pipe',
    displayName: 'GI Foundation Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Foundation Pipe (3\'\' x 2 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 3\'\' x 2 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-7',
    slug: 'polyhouse-gi-column-pipe',
    name: 'GI Column Pipe',
    displayName: 'GI Column Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Column Pipe (2.5\'\' x 2 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 2.5\'\' x 2 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-8',
    slug: 'polyhouse-gi-arch-bottom-pipe',
    name: 'GI Arch Bottom Pipe',
    displayName: 'GI Arch Bottom Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Arch Bottom Pipe (2\'\' x 1.6 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 2\'\' x 1.6 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-9',
    slug: 'polyhouse-gi-arch-pipe-5-5-4-5',
    name: 'GI Arch Pipe (5.5 & 4.5)',
    displayName: 'GI Arch Pipe (5.5 & 4.5)',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Arch Pipe (5.5 & 4.5) (1.25\'\' x 1.6 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 1.25\'\' x 1.6 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-10',
    slug: 'polyhouse-gi-arch-support-pipe',
    name: 'GI Arch Support Pipe',
    displayName: 'GI Arch Support Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Arch Support Pipe (1\'\' x 1.6 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 1\'\' x 1.6 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-11',
    slug: 'polyhouse-gi-purline-pipe',
    name: 'GI Purline Pipe',
    displayName: 'GI Purline Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Purline Pipe (1.5\'\' x 1.6 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 1.5\'\' x 1.6 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-12',
    slug: 'polyhouse-gi-hockey-pipe',
    name: 'GI Hockey Pipe',
    displayName: 'GI Hockey Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Hockey Pipe (1.5\'\' x 1.6 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 1.5\'\' x 1.6 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-13',
    slug: 'polyhouse-gi-compound-pipe',
    name: 'GI Compound Pipe',
    displayName: 'GI Compound Pipe',
    brand: 'Shankara Buildpro',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'GI Structure Pipes',
    price: 120,
    mrp: 142,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'GI Compound Pipe (1.25\'\' x 1.6 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 1.25\'\' x 1.6 mm. Sold per kg.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'gi-structure-pipes'],
    unit: 'per kg',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-14',
    slug: 'polyhouse-shade-net-50-percent-uv',
    name: 'Shade Net (50 Percent UV)',
    displayName: 'Shade Net (50 Percent UV)',
    brand: 'IGO Polyhouse',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Covering Materials',
    price: 33,
    mrp: 39,
    discount: 15,
    stock: 150,
    images: ['/catalog/nursery-essentials/shade-net.jpg'],
    description: 'Shade Net (50 Percent UV) (50/100 m roll) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 50/100 m roll. Sold per sq.mt.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'covering-materials'],
    unit: 'per sq.mt',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-15',
    slug: 'polyhouse-inline-lateral-16-mm-2-lph',
    name: 'Inline Lateral 16 mm (2 LPH)',
    displayName: 'Inline Lateral 16 mm (2 LPH)',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 19,
    mrp: 22,
    discount: 14,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'Inline Lateral 16 mm (2 LPH) (30/40 cm spacing) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 30/40 cm spacing. Sold per metre.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per metre',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-16',
    slug: 'polyhouse-plain-lateral-16-mm',
    name: 'Plain Lateral 16 mm',
    displayName: 'Plain Lateral 16 mm',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 15,
    mrp: 18,
    discount: 17,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'Plain Lateral 16 mm (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per metre.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per metre',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-17',
    slug: 'polyhouse-jain-fogger-medium-pressure',
    name: 'Jain Fogger (Medium Pressure)',
    displayName: 'Jain Fogger (Medium Pressure)',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 143,
    mrp: 169,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/sprinkler-system.webp'],
    description: 'Jain Fogger (Medium Pressure) (Medium pressure) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: Medium pressure. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-18',
    slug: 'polyhouse-grommet-16-mm',
    name: 'Grommet 16 mm',
    displayName: 'Grommet 16 mm',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 6,
    mrp: 7,
    discount: 14,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'Grommet 16 mm (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-19',
    slug: 'polyhouse-take-off-16-mm',
    name: 'Take Off 16 mm',
    displayName: 'Take Off 16 mm',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 4,
    mrp: 5,
    discount: 20,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'Take Off 16 mm (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-20',
    slug: 'polyhouse-mini-valve-16-mm',
    name: 'Mini Valve 16 mm',
    displayName: 'Mini Valve 16 mm',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 37,
    mrp: 44,
    discount: 16,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'Mini Valve 16 mm (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-21',
    slug: 'polyhouse-pvc-elbow-16-mm',
    name: 'PVC Elbow 16 mm',
    displayName: 'PVC Elbow 16 mm',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 5,
    mrp: 6,
    discount: 17,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'PVC Elbow 16 mm (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-22',
    slug: 'polyhouse-pvc-joiner-16-mm',
    name: 'PVC Joiner 16 mm',
    displayName: 'PVC Joiner 16 mm',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 3,
    mrp: 4,
    discount: 25,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'PVC Joiner 16 mm (16 mm) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 16 mm. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-23',
    slug: 'polyhouse-end-stop-16-mm-8-shape',
    name: 'End Stop 16 mm (8-shape)',
    displayName: 'End Stop 16 mm (8-shape)',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 3,
    mrp: 4,
    discount: 25,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'End Stop 16 mm (8-shape) (8 shape) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 8 shape. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-24',
    slug: 'polyhouse-venturi-injector',
    name: 'Venturi Injector',
    displayName: 'Venturi Injector',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 2730,
    mrp: 3221,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Venturi Injector (1.25\'\') - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 1.25\'\'. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-25',
    slug: 'polyhouse-disc-filter',
    name: 'Disc Filter',
    displayName: 'Disc Filter',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 5580,
    mrp: 6584,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Disc Filter (2\'\') - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 2\'\'. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-26',
    slug: 'polyhouse-screen-filter',
    name: 'Screen Filter',
    displayName: 'Screen Filter',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 5720,
    mrp: 6750,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Screen Filter (2\'\') - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 2\'\'. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-27',
    slug: 'polyhouse-sand-filter',
    name: 'Sand Filter',
    displayName: 'Sand Filter',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 22887,
    mrp: 27007,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Sand Filter (2\'\') - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 2\'\'. Sold per set.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per set',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-28',
    slug: 'polyhouse-silica-sand-bag',
    name: 'Silica Sand Bag',
    displayName: 'Silica Sand Bag',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 494,
    mrp: 583,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Silica Sand Bag (30 kg) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 30 kg. Sold per bag.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per bag',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-29',
    slug: 'polyhouse-air-release-valve',
    name: 'Air Release Valve',
    displayName: 'Air Release Valve',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 423,
    mrp: 499,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Air Release Valve (Standard) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: Standard. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-30',
    slug: 'polyhouse-pressure-gauge',
    name: 'Pressure Gauge',
    displayName: 'Pressure Gauge',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 553,
    mrp: 653,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/farm-irrigation.webp'],
    description: 'Pressure Gauge (Glycerine filled) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: Glycerine filled. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-31',
    slug: 'polyhouse-pvc-pipe-2',
    name: 'PVC Pipe 2\'\'',
    displayName: 'PVC Pipe 2\'\'',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 488,
    mrp: 576,
    discount: 15,
    stock: 150,
    images: ['/catalog/irrigation-systems/water-pipes.webp'],
    description: 'PVC Pipe 2\'\' (6 m length) - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 6 m length. Sold per length.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per length',
    isOrganic: false,
    crops: ['Protected cultivation']
  },
  {
    id: 'prod-poly-32',
    slug: 'polyhouse-pvc-elbow-2',
    name: 'PVC Elbow 2\'\'',
    displayName: 'PVC Elbow 2\'\'',
    brand: 'Jain Irrigation',
    category: 'Greenhouse & Polyhouse',
    subcategory: 'Drip & Irrigation',
    price: 4,
    mrp: 5,
    discount: 20,
    stock: 150,
    images: ['/catalog/irrigation-systems/drip-irrigation.webp'],
    description: 'PVC Elbow 2\'\' (2\'\') - genuine polyhouse-grade component for greenhouse and polyhouse construction. Part of the complete IGO Agri Mart polyhouse build kit: foundation, GI structure, covering and drip irrigation supplied from verified partners and quality-checked before dispatch.',
    composition: 'Specification: 2\'\'. Sold per piece.',
    usage: 'For polyhouse / greenhouse construction and fertigation systems. Installation guidance available from IGO Expert Services.',
    rating: 4.7,
    reviewCount: 12,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['polyhouse', 'greenhouse', 'drip-irrigation'],
    unit: 'per piece',
    isOrganic: false,
    crops: ['Protected cultivation']
  }
];
