import { Product, Category, Brand, Service, Course, BlogPost } from './types';

export const SEED_BRANDS: Brand[] = [
  // IGO Own Brands
  { id: 'igo-pf', name: 'IGO Precision Farming', type: 'igo_own' },
  { id: 'igo-fa', name: 'IGO Farm Automation', type: 'igo_own' },
  { id: 'igo-pc', name: 'IGO Protein Cuts', type: 'igo_own' },
  { id: 'igo-ae', name: 'IGO Agri Estates', type: 'igo_own' },
  { id: 'igo-fl', name: 'IGO Farm Loans', type: 'igo_own' },
  { id: 'igo-ac', name: 'IGO Academy', type: 'igo_own' },
  { id: 'igo-ex', name: 'IGO Exports & Imports', type: 'igo_own' },
  { id: 'igo-bs', name: 'IGO Bio Solutions', type: 'igo_own' },
  { id: 'igo-gh', name: 'IGO Greenhouse', type: 'igo_own' },
  { id: 'igo-sd', name: 'IGO Seeds', type: 'igo_own' },
  { id: 'igo-ft', name: 'IGO Fertigation', type: 'igo_own' },
  { id: 'igo-ds', name: 'IGO Drone Services', type: 'igo_own' },
  { id: 'igo-ff', name: 'Farmers Factory', type: 'igo_own' },
  // Third Party Brands
  { id: 'syngenta', name: 'Syngenta', type: 'third_party' },
  { id: 'upl', name: 'UPL', type: 'third_party' },
  { id: 'dhanuka', name: 'Dhanuka', type: 'third_party' },
  { id: 'stihl', name: 'STIHL', type: 'third_party' },
  { id: 'tata-rallis', name: 'Tata Rallis', type: 'third_party' },
  { id: 'coromandel', name: 'Coromandel', type: 'third_party' },
  { id: 'fmc', name: 'FMC', type: 'third_party' },
  { id: 'corteva', name: 'Corteva', type: 'third_party' },
  { id: 't-stanes', name: 'T-Stanes', type: 'third_party' },
  { id: 'multiplex', name: 'Multiplex', type: 'third_party' },
  { id: 'katyayani', name: 'Katyayani', type: 'third_party' }
];

export const SEED_CATEGORIES: Category[] = [
  { id: 'seeds-saplings', name: 'Seeds & Saplings', slug: 'seeds-saplings', icon: 'Sprout', productCount: 5 },
  { id: 'fertilizers', name: 'Fertilizers', slug: 'fertilizers', icon: 'Leaf', productCount: 5 },
  { id: 'crop-care', name: 'Crop Care', slug: 'crop-care', icon: 'ShieldAlert', productCount: 5 },
  { id: 'bioproducts', name: 'Bioproducts', slug: 'bioproducts', icon: 'Activity', productCount: 5 },
  { id: 'farm-implements', name: 'Farm Implements', slug: 'farm-implements', icon: 'Hammer', productCount: 5 },
  { id: 'farm-automation', name: 'Farm Automation', slug: 'farm-automation', icon: 'Cpu', productCount: 5 },
  { id: 'protein-cuts', name: 'Protein Cuts', slug: 'protein-cuts', icon: 'Beef', productCount: 5 },
  { id: 'garden-care', name: 'Garden Care', slug: 'garden-care', icon: 'Flower2', productCount: 5 }
];

export const SEED_PRODUCTS: Product[] = [
  // Category 1: Seeds & Saplings (tomato, okra, chilli, onion, cucumber)
  {
    id: 'prod-seeds-01',
    name: 'IGO Hybrid Tomato Seeds - Swaraksha Plus',
    slug: 'igo-hybrid-tomato-seeds-swaraksha-plus',
    brand: 'IGO Seeds',
    category: 'Seeds & Saplings',
    subcategory: 'Vegetables',
    price: 320,
    mrp: 450,
    discount: 28,
    stock: 120,
    images: [
      'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80'
    ],
    description: 'High-yielding hybrid tomato seeds perfect for southern states of India. Yields firm, glossy red medium-sized tomatoes with excellent shelf life for transport. Tolerant to tomato leaf curl virus.',
    composition: 'Hybrid F1 Solanum Lycopersicum Seeds. Purity > 98%. Germination > 85%.',
    usage: 'Sow in seedling trays with vermicompost. Transplant after 21-25 days. Maintain optimum soil moisture.',
    rating: 4.8,
    reviewCount: 42,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['seeds', 'tomato', 'hybrid', 'vegetables']
  },
  {
    id: 'prod-seeds-02',
    name: 'Syngenta Premium Cucumber Seeds (Crispy Green)',
    slug: 'syngenta-premium-cucumber-seeds-crispy-green',
    brand: 'Syngenta',
    category: 'Seeds & Saplings',
    subcategory: 'Vegetables',
    price: 490,
    mrp: 600,
    discount: 18,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=600&q=80'],
    description: 'Crispy green cucumber hybrid seeds with strong vigor. High uniform shape fruit output with appetizing dark-green color. Crisp texture and bitter-free pulp.',
    composition: 'F1 Hybrid Cucumber (Cucumis sativus) seeds. Germination min 82%.',
    usage: 'Direct sowing on ridges or hills. Space rows 1.5m apart. Requires regular light watering.',
    rating: 4.5,
    reviewCount: 29,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['seeds', 'cucumber', 'syngenta', 'vegetable']
  },
  {
    id: 'prod-seeds-03',
    name: 'Farmers Factory Hybrid Okra Seeds (Bhindi-77)',
    slug: 'farmers-factory-hybrid-okra-seeds-bhindi-77',
    brand: 'Farmers Factory',
    category: 'Seeds & Saplings',
    subcategory: 'Vegetables',
    price: 180,
    mrp: 250,
    discount: 28,
    stock: 200,
    images: ['https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=600&q=80'],
    description: 'Superb tender-dark-green hybrid okra seeds. High-tolerance to Yellow Vein Mosaic Virus (YVMV). Quick germination and high picking frequency.',
    composition: 'Hybrid Okra F1 Seeds. Genetic purity 99%.',
    usage: 'Sow seeds directly 1 inch deep in warm, well-draining soil. Irrigation once in 4 days.',
    rating: 4.7,
    reviewCount: 56,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['seeds', 'okra', 'bhindi', 'vegetables']
  },
  {
    id: 'prod-seeds-04',
    name: 'IGO Tejas Chilli Seeds (Super Hot Line)',
    slug: 'igo-tejas-chilli-seeds-super-hot-line',
    brand: 'IGO Seeds',
    category: 'Seeds & Saplings',
    subcategory: 'Vegetables',
    price: 360,
    mrp: 480,
    discount: 25,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=600&q=80'],
    description: 'Very hot selection of Indian green/red chilli hybrid seeds. Excellent heat tolerance and dark green pungent fruits turning glossy dark red upon maturity.',
    composition: 'Premium Hybrid F1 Capsicum Annuum seeds.',
    usage: 'Raise nurseries in shade. Transplant 4-5 week seedlings. High requirement of organic manure.',
    rating: 4.6,
    reviewCount: 31,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['seeds', 'chilli', 'spicy', 'igo_seeds']
  },
  {
    id: 'prod-seeds-05',
    name: 'Corteva Golden Onion Seeds (Nasik Red Globe)',
    slug: 'corteva-golden-onion-seeds-nasik-red-globe',
    brand: 'Corteva',
    category: 'Seeds & Saplings',
    subcategory: 'Vegetables',
    price: 450,
    mrp: 550,
    discount: 18,
    stock: 95,
    images: ['https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=600&q=80'],
    description: 'Famous Nasik Red Globe onion seed variety. Produces medium-large uniform deep-red globes with excellent dry-skin quality for extended storage.',
    composition: 'Allium Cepa OP Seeds. Purity 98%.',
    usage: 'Sow in well-pulverized beds. Transplant after 45 days. Keep fields free of weeds.',
    rating: 4.4,
    reviewCount: 18,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['seeds', 'onion', 'nasik-red', 'corteva']
  },

  // Category 2: Fertilizers (NPK, micronutrients, secondary, growth regulators)
  {
    id: 'prod-fert-01',
    name: 'Coromandel NPK 19:19:19 Soluble Fertilizer',
    slug: 'coromandel-npk-19-19-19-soluble-fertilizer',
    brand: 'Coromandel',
    category: 'Fertilizers',
    subcategory: 'Major Nutrients (NPK)',
    price: 240,
    mrp: 350,
    discount: 31,
    stock: 500,
    images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80'],
    description: '100% water-soluble foliage fertilizer containing high-grade Nitrogen, Phosphorus, and Potassium. Boosts vegetative growth, root expansion, and crop luster.',
    composition: 'Nitrogen (19%), P2O5 (19%), K2O (19%) dry mineral salts.',
    usage: 'Foliar spray: 5g per Litre of water. Fertigation: 3-5 kg per acre depending on crop stage.',
    rating: 4.7,
    reviewCount: 112,
    isIgoOwn: false,
    problemFilter: 'Manures & Fertilizers',
    tags: ['fertilizer', 'npk', 'soluble', 'growth']
  },
  {
    id: 'prod-fert-02',
    name: 'Multiplex Multi-Micronutrient Liquid Booster (Crops)',
    slug: 'multiplex-multi-micronutrient-liquid-booster-crops',
    brand: 'Multiplex',
    category: 'Fertilizers',
    subcategory: 'Micronutrients',
    price: 380,
    mrp: 490,
    discount: 22,
    stock: 250,
    images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80'],
    description: 'Enriched formulation of essential trace elements like Zinc, Iron, Manganese, Boron, Copper, and Molybdenum. Corrects nutritional yellowing and flower drops.',
    composition: 'Zn 3.0%, Fe 2.0%, Mn 1.0%, B 0.5% in fully chelated organic form.',
    usage: 'Mix 2.5ml in 1 Litre of clean water and spray evenly on both sides of leaves.',
    rating: 4.5,
    reviewCount: 78,
    isIgoOwn: false,
    problemFilter: 'Growth Boosters',
    tags: ['micronutrient', 'foliar', 'liquid', 'multiplex']
  },
  {
    id: 'prod-fert-03',
    name: 'IGO Precision Ferti-Max Growth Regulator',
    slug: 'igo-precision-ferti-max-growth-regulator',
    brand: 'IGO Precision Farming',
    category: 'Fertilizers',
    subcategory: 'Plant Growth Regulators',
    price: 650,
    mrp: 850,
    discount: 23,
    stock: 140,
    images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80'],
    description: 'Premium growth regulatory and cell elongator designed to increase fruit/vegetable size, color uniformity, and post-harvest shelf strength.',
    composition: 'Gibberellic Acid 0.001% L and natural seaweed stimulants.',
    usage: 'Apply 1ml/Litre during early blossoming stages. Repeat after 15 days.',
    rating: 4.9,
    reviewCount: 61,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['pgr', 'gibberellic', 'seaweed', 'igo']
  },
  {
    id: 'prod-fert-04',
    name: 'Tata Rallis Solubor Chelated Boron (20%)',
    slug: 'tata-rallis-solubor-chelated-boron-20',
    brand: 'Tata Rallis',
    category: 'Fertilizers',
    subcategory: 'Micronutrients',
    price: 290,
    mrp: 380,
    discount: 23,
    stock: 320,
    images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80'],
    description: 'Water-soluble Di-Sodium Octa Borate Tetra Hydrate containing 20% elemental Boron. Crucial for pollen gestation, flowering, and sugar translocation.',
    composition: 'Disodium Octaborate Tetrahydrate (Boron 20% Min).',
    usage: '1 - 1.5 grams per Litre of water during pre-flowering and fruit-set stages.',
    rating: 4.6,
    reviewCount: 45,
    isIgoOwn: false,
    problemFilter: 'Manures & Fertilizers',
    tags: ['boron', 'micronutrient', 'tata', 'solubor']
  },
  {
    id: 'prod-fert-05',
    name: 'IGO Fertigation Secondary Nutrients calcium-magnesium combo',
    slug: 'igo-fertigation-secondary-nutrients-calcium-magnesium-combo',
    brand: 'IGO Fertigation',
    category: 'Fertilizers',
    subcategory: 'Secondary Nutrients',
    price: 450,
    mrp: 600,
    discount: 25,
    stock: 180,
    images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80'],
    description: 'Powerful crystalline blend of Calcium Nitrate and Magnesium Sulfate. Vital for plant cell walls, chlorophyll generation, and prevention of blossom end rot in tomatoes.',
    composition: 'Calcium 18.8%, Magnesium 9.5% with organic solubility tags.',
    usage: 'Drip fertigation: 5 kg per acre. Root drenching: 3g per Litre.',
    rating: 4.8,
    reviewCount: 39,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['calcium', 'magnesium', 'secondary-nutrients', 'igo']
  },

  // Category 3: Crop Care (insecticides, fungicides, herbicides, seed treatments)
  {
    id: 'prod-care-01',
    name: 'FMC Coragen Broad-Spectrum Insecticide',
    slug: 'fmc-coragen-broad-spectrum-insecticide',
    brand: 'FMC',
    category: 'Crop Care',
    subcategory: 'Insecticides',
    price: 1850,
    mrp: 2200,
    discount: 15,
    stock: 110,
    images: ['https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80'],
    description: 'Gold standard insecticide for control of devastating pests like stem borers in paddy, fruit borers in tomatoes, and diamondback moth in cabbage.',
    composition: 'Chlorantraniliprole 18.5% w/w Suspension Concentrate (SC).',
    usage: 'Apply at 60ml to 80ml per acre in 200 Litres of water using flat fan nozzle spray.',
    rating: 4.9,
    reviewCount: 204,
    isIgoOwn: false,
    problemFilter: 'Pest Control',
    tags: ['insecticide', 'pests', 'coragen', 'fmc']
  },
  {
    id: 'prod-care-02',
    name: 'Syngenta Amistar Top Fungicide',
    slug: 'syngenta-amistar-top-fungicide',
    brand: 'Syngenta',
    category: 'Crop Care',
    subcategory: 'Fungicides',
    price: 2450,
    mrp: 2850,
    discount: 14,
    stock: 90,
    images: ['https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80'],
    description: 'State of the art systemic fungicide with dual active actions. Controls powdery mildew, leaf spot, early and late blight in high-value vegetable crops.',
    composition: 'Azoxystrobin 18.2% + Difenoconazole 11.4% SC.',
    usage: '1ml per Litre of water. Apply at the first onset of atmospheric Humidity or spot signs.',
    rating: 4.8,
    reviewCount: 118,
    isIgoOwn: false,
    problemFilter: 'Disease Control',
    tags: ['fungicide', 'blight', 'mildew', 'syngenta']
  },
  {
    id: 'prod-care-03',
    name: 'UPL Saaf Systemic and Contact Fungicide',
    slug: 'upl-saaf-systemic-and-contact-fungicide',
    brand: 'UPL',
    category: 'Crop Care',
    subcategory: 'Fungicides',
    price: 380,
    mrp: 500,
    discount: 24,
    stock: 450,
    images: ['https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80'],
    description: 'Widely popular dual contact & systemic fungicide with multisite action. Highly trusted by Indian orchard growers and smallholder farmers.',
    composition: 'Carbendazim 12% + Mancozeb 63% WP.',
    usage: '2 grams per Litre of water for foliar spraying; 2.5 grams per kg of seeds for seed treatment.',
    rating: 4.7,
    reviewCount: 340,
    isIgoOwn: false,
    problemFilter: 'Disease Control',
    tags: ['saaf', 'upl', 'fungi', 'mildew']
  },
  {
    id: 'prod-care-04',
    name: 'Katyayani Organic Neem Oil Crop Protectant',
    slug: 'katyayani-organic-neem-oil-crop-protectant',
    brand: 'Katyayani',
    category: 'Crop Care',
    subcategory: 'Seed Treatment',
    price: 499,
    mrp: 750,
    discount: 33,
    stock: 350,
    images: ['https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80'],
    description: 'Pure, organic, cold-pressed Neem Oil containing high levels of Azadirachtin. Destroys over 200 biting/chewing pest species naturally while remaining pollinator friendly.',
    composition: 'Cold-pressed Neem Oil with natural emulsifier 10,000 PPM Azadirachtin.',
    usage: 'Dilute 3-5ml in 1 Litre of lukewarm water, shake well and spray early morning or late evening.',
    rating: 4.6,
    reviewCount: 92,
    isIgoOwn: false,
    problemFilter: 'Pest Control',
    tags: ['neem-oil', 'organic', 'pesticide', 'katyayani']
  },
  {
    id: 'prod-care-05',
    name: 'Dhanuka Targa Super Selective Herbicide',
    slug: 'dhanuka-targa-super-selective-herbicide',
    brand: 'Dhanuka',
    category: 'Crop Care',
    subcategory: 'Herbicides',
    price: 820,
    mrp: 1100,
    discount: 25,
    stock: 120,
    images: ['https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80'],
    description: 'Elite selective herbicide designed to eradicate narrow-leaf grassy weeds in broad-leaf crops like soy, oilseeds, cotton, and vegetables.',
    composition: 'Quizalofop-Ethyl 5% EC.',
    usage: 'Post-emergence at 300ml to 400ml per acre mixed in 200 Litres of clean water.',
    rating: 4.5,
    reviewCount: 52,
    isIgoOwn: false,
    problemFilter: 'Pest Control',
    tags: ['herbicide', 'weeds', 'dhanuka', 'selective']
  },

  // Category 4: Bioproducts (organic manure, biofungicide, biofertilizer, bioinsecticide)
  {
    id: 'prod-bio-01',
    name: 'IGO Bio Solutions Organic Seaweed Extract',
    slug: 'igo-bio-solutions-organic-seaweed-extract',
    brand: 'IGO Bio Solutions',
    category: 'Bioproducts',
    subcategory: 'Organic Manures',
    price: 390,
    mrp: 550,
    discount: 29,
    stock: 300,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80'],
    description: 'Certified organic bio-fertilizer extracted from marine brown algae. Contains natural plant hormone catalysts like auxins and cytokinins to trigger vigorous growth.',
    composition: 'Sargassum Seaweed dry solids, natural organic humic acids (12%).',
    usage: 'Apply 2ml per Litre of water via foliar spray or 1 Litre per acre via irrigation line.',
    rating: 4.8,
    reviewCount: 88,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['seaweed', 'organic', 'biostimulant', 'igo']
  },
  {
    id: 'prod-bio-02',
    name: 'T-Stanes Bio-Power Trichoderma Viride Biofungicide',
    slug: 't-stanes-bio-power-trichoderma-viride-biofungicide',
    brand: 'T-Stanes',
    category: 'Bioproducts',
    subcategory: 'Biofungicide',
    price: 220,
    mrp: 300,
    discount: 26,
    stock: 400,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80'],
    description: 'Eco-certified microbial biofungicide containing highly active antagonistic Trichoderma spores. Rapidly colonizes roots to prevent root wilt, collar rot and damping off.',
    composition: 'Trichoderma Viride active live spores 1.5% WP (min 10^8 CFU/g).',
    usage: 'Soil application: 2.5 kg mixed in 100 kg farmyard manure per acre. Seed coating: 10g per kg of seeds.',
    rating: 4.6,
    reviewCount: 130,
    isIgoOwn: false,
    problemFilter: 'Disease Control',
    tags: ['trichoderma', 'biofungicide', 'stanes', 'organic']
  },
  {
    id: 'prod-bio-03',
    name: 'IGO Premium Liquid Rhizobium Biofertilizer',
    slug: 'igo-premium-liquid-rhizobium-biofertilizer',
    brand: 'IGO Bio Solutions',
    category: 'Bioproducts',
    subcategory: 'Biofertilizer',
    price: 290,
    mrp: 400,
    discount: 27,
    stock: 220,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80'],
    description: 'Ultra-concentrated liquid nitrogen fixing bacteria designed for pulse and leguminous crops. Promotes rapid root nodule formation and captures atmospheric nitrogen.',
    composition: 'Rhizobium Leguminosarum live active liquid cell count 10^9 cells/ml.',
    usage: 'Seed treatment: 250ml per 10kg seeds. Soil: 500ml per acre through drip.',
    rating: 4.9,
    reviewCount: 41,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['rhizobium', 'biofertilizer', 'nitrogen', 'igo']
  },
  {
    id: 'prod-bio-04',
    name: 'Multiplex Bio-Strike Metarhizium Bioinsecticide',
    slug: 'multiplex-bio-strike-metarhizium-bioinsecticide',
    brand: 'Multiplex',
    category: 'Bioproducts',
    subcategory: 'Bioinsecticide',
    price: 280,
    mrp: 350,
    discount: 20,
    stock: 260,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80'],
    description: 'Entomopathogenic bio-pesticide designed to target root-damaging insect larvae, including white grubs, root beetles and termites naturally.',
    composition: 'Metarhizium Anisopliae dry fungal spores (standard 1x10^8 viable counts/gm).',
    usage: 'Mix 5g per Litre of water and drench roots thoroughly, preferably in late evenings.',
    rating: 4.7,
    reviewCount: 65,
    isIgoOwn: false,
    problemFilter: 'Pest Control',
    tags: ['metarhizium', 'bioinsecticide', 'multiplex', 'grubs']
  },
  {
    id: 'prod-bio-05',
    name: 'IGO Bio Solutions Premium Humic-Amino Acid Granules',
    slug: 'igo-bio-solutions-premium-humic-amino-acid-granules',
    brand: 'IGO Bio Solutions',
    category: 'Bioproducts',
    subcategory: 'Organic Manures',
    price: 480,
    mrp: 650,
    discount: 26,
    stock: 190,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80'],
    description: 'Rich organic bentonite coated soil conditioner. Enhances soil structure, unlocks dormant minerals, improves moisture retention and feeds beneficial microbes.',
    composition: 'Humic Acid 15%, Amino Acid 5%, Fulvic Acid 5% on slow release mineral base.',
    usage: 'Broadcasting: 5-8 kg per acre at land preparation or early crop stages.',
    rating: 4.8,
    reviewCount: 74,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['humic', 'amino-acid', 'soil-conditioner', 'igo']
  },

  // Category 5: Farm Implements (machinery, hand tools, irrigation)
  {
    id: 'prod-work-01',
    name: 'STIHL FS-120 Heavy-Duty Professional Brush Cutter',
    slug: 'stihl-fs-120-heavy-duty-professional-brush-cutter',
    brand: 'STIHL',
    category: 'Farm Implements',
    subcategory: 'Machinery',
    price: 24900,
    mrp: 29500,
    discount: 15,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80'],
    description: 'High-power displacement brush cutter and grass trimmer built by STIHL. Perfect for clearing dense, thick weed areas, grass tufts and wood stems over vast acres.',
    composition: '1.3 kW (1.8 HP) petrol displacement engine, heavy shaft, double shoulder harness.',
    usage: 'Add 2T oil in petrol (1:50 mix). Clean air filter weekly. Wear proper facial and protective gear.',
    rating: 4.9,
    reviewCount: 52,
    isIgoOwn: false,
    problemFilter: 'Pest Control',
    tags: ['brush-cutter', 'mower', 'stihl', 'engine']
  },
  {
    id: 'prod-work-02',
    name: 'Farmers Factory High-Pressure Battery Knapsack Sprayer',
    slug: 'farmers-factory-high-pressure-battery-knapsack-sprayer',
    brand: 'Farmers Factory',
    category: 'Farm Implements',
    subcategory: 'Machinery',
    price: 2200,
    mrp: 3500,
    discount: 37,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80'],
    description: '2-in-1 battery cum manual 16-litre spray container. Driven by a robust 12V 8Ah sealed lead-acid battery. Sprays continuously up to 25 barrels on one full charge.',
    composition: 'ABS Plastic Body, 12V dry battery, stainless steel adjustable lance, multi nozzle set.',
    usage: 'Fully charge battery before first use. Flush tank with clean water after spraying chemicals.',
    rating: 4.7,
    reviewCount: 148,
    isIgoOwn: true,
    tags: ['sprayer', 'battery', 'knapsack', 'factory']
  },
  {
    id: 'prod-work-03',
    name: 'IGO Precision Heavy Earth Auger (63CC Engine)',
    slug: 'igo-precision-heavy-earth-auger-63cc-engine',
    brand: 'IGO Precision Farming',
    category: 'Farm Implements',
    subcategory: 'Machinery',
    price: 9900,
    mrp: 13500,
    discount: 26,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80'],
    description: 'Heavy duty, single person petrol engine earth auger. Perfect for digging sapling plantation pits, fence pole holes and solar mounting foundations.',
    composition: '63CC Two-stroke air-cooled engine, includes 8-inch robust drill bit.',
    usage: 'Requires petrol 2T oil mix. Dig on stable vertical stance. Block stones and roots from direct contact.',
    rating: 4.8,
    reviewCount: 23,
    isIgoOwn: true,
    tags: ['auger', 'digging', 'earth-drill', 'igo']
  },
  {
    id: 'prod-work-04',
    name: 'STIHL GTA 26 Garden Handy Battery Pruning Saw',
    slug: 'stihl-gta-26-garden-handy-battery-pruning-saw',
    brand: 'STIHL',
    category: 'Farm Implements',
    subcategory: 'Machinery',
    price: 8500,
    mrp: 10000,
    discount: 15,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80'],
    description: 'Lightweight cordless, handheld mini wood saw cutter. Best for clipping orchard branches, garden structural repairs and wood shaping.',
    composition: '10.8V Lithium-ion battery system, 4-inch guiding bar sequence.',
    usage: 'Requires light guide-chain oiling. Apply gently on twigs with minimal compression.',
    rating: 4.8,
    reviewCount: 37,
    isIgoOwn: false,
    tags: ['wood-cutter', 'pruner', 'stihl', 'cordless']
  },
  {
    id: 'prod-work-05',
    name: 'Farmers Factory High-Strength Carbon Steel Hand Weeder',
    slug: 'farmers-factory-high-strength-carbon-steel-hand-weeder',
    brand: 'Farmers Factory',
    category: 'Farm Implements',
    subcategory: 'Hand Tools',
    price: 350,
    mrp: 500,
    discount: 30,
    stock: 250,
    images: ['https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80'],
    description: 'Lightweight, ergonomically shaped hand tool for manual scraping and weed clearing in nursery rows, kitchen gardens, and vegetable patches.',
    composition: 'Tempered high-carbon steel blade with anti-rust paint and firm wood handle.',
    usage: 'Slice weeds below soil surfaces. Wipe clean with oily cloth after usage.',
    rating: 4.6,
    reviewCount: 89,
    isIgoOwn: true,
    problemFilter: 'Pest Control',
    tags: ['weeder', 'hand-tool', 'weeds', 'garden']
  },

  // Category 6: Farm Automation (drip systems, sensors, drone services)
  {
    id: 'prod-auto-01',
    name: 'IGO Farm Automation Custom Drip Irrigation Kit',
    slug: 'igo-farm-automation-custom-drip-irrigation-kit',
    brand: 'IGO Farm Automation',
    category: 'Farm Automation',
    subcategory: 'Drip Systems',
    price: 2850,
    mrp: 4200,
    discount: 32,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80'],
    description: 'Comprehensive smart micro-irrigation set perfect for 1/4 acre vegetable cropping. Features pressure compensation emitters and UV stabilized lateral tubes.',
    composition: '16mm Main Lateral line tubes, 40 drip emitters, filter, valves, punch tools.',
    usage: 'Set up pipes along vegetable beds. Connect back flush filter to water main.',
    rating: 4.9,
    reviewCount: 67,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['drip-irrigation', 'pipes', 'water-saving', 'igo']
  },
  {
    id: 'prod-auto-02',
    name: 'IGO Precision Wireless Soil Moisture Sensor Kit',
    slug: 'igo-precision-wireless-soil-moisture-sensor-kit',
    brand: 'IGO Precision Farming',
    category: 'Farm Automation',
    subcategory: 'Sensor Kits',
    price: 4500,
    mrp: 6500,
    discount: 30,
    stock: 60,
    images: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80'],
    description: 'IoT automated smart sensor to monitor soil moisture, NPK trace hints, pH balances, and temperature in real-time. Syncs directly with India Green App via Bluetooth.',
    composition: 'Industrial grade stainless steel forks, digital display sender unit, app access.',
    usage: 'Insert steel probes 6 inches deep in root zones. Open Mobile App to view metrics.',
    rating: 4.8,
    reviewCount: 31,
    isIgoOwn: true,
    tags: ['iot', 'sensor', 'soil-sensor', 'igo_precision']
  },
  {
    id: 'prod-auto-03',
    name: 'IGO Drone Services Complete Farm Spray Service Voucher',
    slug: 'igo-drone-services-complete-farm-spray-service-voucher',
    brand: 'IGO Drone Services',
    category: 'Farm Automation',
    subcategory: 'Drone Services',
    price: 1500,
    mrp: 2000,
    discount: 25,
    stock: 1000,
    images: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80'],
    description: 'Prepaid service voucher for drone based crop protection spray. Covers 1 Acre of farm land. Speeds up application, prevents water wastage, and avoids physical chemical contact.',
    composition: 'Standard 1-acre autonomous hexacopter spraying service by certified pilot.',
    usage: 'Redeem via toll free or app. Pilot will visit site inside 3 working days.',
    rating: 4.9,
    reviewCount: 75,
    isIgoOwn: true,
    problemFilter: 'Pest Control',
    tags: ['drone', 'service', 'spray', 'igo_drone']
  },
  {
    id: 'prod-auto-04',
    name: 'IGO Greenhouse Automated Mist Control Valve',
    slug: 'igo-greenhouse-automated-mist-control-valve',
    brand: 'IGO Greenhouse',
    category: 'Farm Automation',
    subcategory: 'Sensor Kits',
    price: 1250,
    mrp: 1800,
    discount: 30,
    stock: 90,
    images: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80'],
    description: 'Solenoid automated water valve that triggers misting jets based on humidity drops. Minimizes orchid/sapling hydration failures inside nursery setups.',
    composition: 'Copper body solenoid valve, 12V timer plug, humidity detection probe.',
    usage: 'Connect behind clean spray jets. Program threshold humidity trigger (e.g., 60%).',
    rating: 4.7,
    reviewCount: 15,
    isIgoOwn: true,
    tags: ['mist', 'solenoid', 'greenhouse', 'igo']
  },
  {
    id: 'prod-auto-05',
    name: 'IGO Precision pH & Temperature Smart Pen',
    slug: 'igo-precision-ph-temperature-smart-pen',
    brand: 'IGO Precision Farming',
    category: 'Farm Automation',
    subcategory: 'Sensor Kits',
    price: 1100,
    mrp: 1500,
    discount: 26,
    stock: 110,
    images: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80'],
    description: 'Pocket friendly digital testing device to examine pH index and temperature of irrigation water or liquid fertigation feeds instantly.',
    composition: 'Highly sensitive glass electrode, digital backlit LCD, auto calibration keys.',
    usage: 'Dip electrode in water feed. Wait 5 seconds for locked numeric value.',
    rating: 4.6,
    reviewCount: 44,
    isIgoOwn: true,
    tags: ['ph-meter', 'tester', 'water', 'smart']
  },

  // Category 7: Protein Cuts (chicken, mutton, seafood, exotic, ready-to-cook)
  {
    id: 'prod-meat-01',
    name: 'IGO Protein Cuts Premium Country Chicken (Premium Nattu Kozhi)',
    slug: 'igo-protein-cuts-premium-country-chicken-premium-nattu-kozhi',
    brand: 'IGO Protein Cuts',
    category: 'Protein Cuts',
    subcategory: 'Chicken',
    price: 420,
    mrp: 550,
    discount: 23,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80'],
    description: 'Premium free-range country chicken reared organically in dynamic pastures in Tamil Nadu. Skinless, lean meat containing delicious authentic village chicken taste.',
    composition: '100% Free range organic country chicken, clean raw bird cuts.',
    usage: 'Keep chilled until use. Perfect for traditional spicy Chettinadu gravy.',
    rating: 4.9,
    reviewCount: 180,
    isIgoOwn: true,
    tags: ['meat', 'chicken', 'country-chicken', 'organic']
  },
  {
    id: 'prod-meat-02',
    name: 'IGO Protein Cuts Tender Curry Cut Mutton (Rich Goat)',
    slug: 'igo-protein-cuts-tender-curry-cut-mutton-rich-goat',
    brand: 'IGO Protein Cuts',
    category: 'Protein Cuts',
    subcategory: 'Mutton',
    price: 850,
    mrp: 990,
    discount: 14,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80'],
    description: 'Juicy, rich, premium goat meat cuts curated from grass-fed local herds. Handpicked tender slices containing perfect fat-to-meat ratios for home curries.',
    composition: 'Skinless organic goat curry cuts, fat bounded below 10%.',
    usage: 'Pressure cook with ginger-garlic paste for tender texture.',
    rating: 4.8,
    reviewCount: 142,
    isIgoOwn: true,
    tags: ['mutton', 'goat', 'meat', 'fresh']
  },
  {
    id: 'prod-meat-03',
    name: 'IGO Protein Cuts Fresh Bay Seafood Shrimp (Prawns Medium)',
    slug: 'igo-protein-cuts-fresh-bay-seafood-shrimp-prawns-medium',
    brand: 'IGO Protein Cuts',
    category: 'Protein Cuts',
    subcategory: 'Seafood',
    price: 590,
    mrp: 750,
    discount: 21,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80'],
    description: 'Locally sourced medium sized clean seawater prawns. Peeled and deveined, packed inside absolute cold-chain logistics to ensure coastal freshness.',
    composition: 'Peeled, deveined seawater prawns without synthetic hydration.',
    usage: 'Rinse in cold water. Cook within 24 hours of package breakout.',
    rating: 4.7,
    reviewCount: 95,
    isIgoOwn: true,
    tags: ['prawns', 'shrimp', 'seafood', 'fresh']
  },
  {
    id: 'prod-meat-04',
    name: 'IGO Protein Cuts Ready-to-Cook Malabar Marinated Fish',
    slug: 'igo-protein-cuts-ready-to-cook-malabar-marinated-fish',
    brand: 'IGO Protein Cuts',
    category: 'Protein Cuts',
    subcategory: 'Exotic',
    price: 380,
    mrp: 480,
    discount: 20,
    stock: 65,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80'],
    description: 'Fresh Seer fish (Vanjaram) steaks marinated in authentic Malabar spice paste. Zero preservatives, zero synthetic coloring.',
    composition: 'Seer fish steaks, red chilli ground, turmeric, tamarind juice, curry leaves.',
    usage: 'Shallow fry on tawa with a dash of coconut oil for 5 minutes each side.',
    rating: 4.8,
    reviewCount: 66,
    isIgoOwn: true,
    tags: ['seer-fish', 'ready-to-cook', 'marinated', 'malabar']
  },
  {
    id: 'prod-meat-05',
    name: 'IGO Protein Cuts Premium Tender Broiler Chicken (Skinless)',
    slug: 'igo-protein-cuts-premium-tender-broiler-chicken-skinless',
    brand: 'IGO Protein Cuts',
    category: 'Protein Cuts',
    subcategory: 'Chicken',
    price: 250,
    mrp: 320,
    discount: 21,
    stock: 120,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80'],
    description: 'Freshly cut, skinless broiler chicken. Cleaned and processed in certified hygienic plants to assure highest safety standards.',
    composition: 'Skinless tender broiler chicken bird cuts.',
    usage: 'Wash cleanly. Best for chicken fry, roast, or deep culinary baking.',
    rating: 4.5,
    reviewCount: 220,
    isIgoOwn: true,
    tags: ['broiler', 'chicken', 'fresh-cut', 'skinless']
  },

  // Category 8: Garden Care (potting soil, coco peat, vermicompost, pesticides)
  {
    id: 'prod-gard-01',
    name: 'Farmers Factory Enriched Organic Potting Soil (10kg Bag)',
    slug: 'farmers-factory-enriched-organic-potting-soil-10kg-bag',
    brand: 'Farmers Factory',
    category: 'Garden Care',
    subcategory: 'Potting Soil',
    price: 290,
    mrp: 450,
    discount: 35,
    stock: 500,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80'],
    description: 'Premium light garden potting soil formulated with coco peat, microbial inoculants, composted leaves and vermitreats. Ready to pot right away.',
    composition: 'Red soil, coco peat, micro nutrients, beneficial fungal cultures.',
    usage: 'Fill pots leaving 1 inch spacer at top. Plant sapling. Water gently.',
    rating: 4.8,
    reviewCount: 154,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['soil', 'potting', 'organic', 'garden']
  },
  {
    id: 'prod-gard-02',
    name: 'IGO Bio Solutions Low-EC Buffered Coco Peat Block (5kg)',
    slug: 'igo-bio-solutions-low-ec-buffered-coco-peat-block-5kg',
    brand: 'IGO Bio Solutions',
    category: 'Garden Care',
    subcategory: 'Coco Peat',
    price: 199,
    mrp: 300,
    discount: 33,
    stock: 600,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80'],
    description: 'Lightly compressed premium coco peat block. Expands up to 75 Litres of fluffy peat when hydrated. Low EC (< 0.5) ensures tender root growth safety.',
    composition: '100% Buffered organic coconut husk fibrous pith.',
    usage: 'Keep block in tub. Add 20 Litres of water. Let it expand. Combine with soil.',
    rating: 4.7,
    reviewCount: 210,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['cocopeat', 'organic', 'soil-less', 'grow-medium']
  },
  {
    id: 'prod-gard-03',
    name: 'Farmers Factory Premium Vermicompost (Organic Gold 5kg)',
    slug: 'farmers-factory-premium-vermicompost-organic-gold-5kg',
    brand: 'Farmers Factory',
    category: 'Garden Care',
    subcategory: 'Vermicompost',
    price: 150,
    mrp: 230,
    discount: 34,
    stock: 800,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80'],
    description: 'Premium odorless pure black earth humus digested by earthworms. Naturally contains high humic contents to stimulate healthy vegetable plants.',
    composition: '100% Pure digested cow-manure organic humus.',
    usage: 'Add a handful (100g) around plant roots once in 15 days. Mix slightly into soil.',
    rating: 4.9,
    reviewCount: 310,
    isIgoOwn: true,
    problemFilter: 'Manures & Fertilizers',
    tags: ['vermicompost', 'earthworm', 'manure', 'organic']
  },
  {
    id: 'prod-gard-04',
    name: 'Multiplex Bio-Fungal Defense Spray (Urban Garden Care)',
    slug: 'multiplex-bio-fungal-defense-spray-urban-garden-care',
    brand: 'Multiplex',
    category: 'Garden Care',
    subcategory: 'Chemical & Organic Pesticides',
    price: 250,
    mrp: 320,
    discount: 21,
    stock: 300,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80'],
    description: 'Pre-diluted organic fungicide spray bottle built for urban balcony gardens. Treats and controls white powdery spots, rust, and leaf curls.',
    composition: 'Aqueous garlic extract, clove oils, biological organic surfactants.',
    usage: 'Spray directly on infected foliage. Apply once in 5 days until spots fade.',
    rating: 4.4,
    reviewCount: 42,
    isIgoOwn: false,
    problemFilter: 'Disease Control',
    tags: ['organic-spray', 'fungi', 'mildew', 'balcony']
  },
  {
    id: 'prod-gard-05',
    name: 'IGO Precision Flower Boost Micro-Feed tabs (50 tabs)',
    slug: 'igo-precision-flower-boost-micro-feed-tabs-50-tabs',
    brand: 'IGO Precision Farming',
    category: 'Garden Care',
    subcategory: 'Chemical & Organic Pesticides',
    price: 360,
    mrp: 480,
    discount: 25,
    stock: 140,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80'],
    description: 'Slow release concentrated feed tablets to trigger heavy rose and jasmine blossoming in home pots.',
    composition: 'Compact dry mineral NPK 10:20:20 enriched with humic boosters.',
    usage: 'Push 2 tablets 1 inch deep close to the pot rim. Water normally. Reapply monthly.',
    rating: 4.8,
    reviewCount: 57,
    isIgoOwn: true,
    problemFilter: 'Growth Boosters',
    tags: ['rose', 'flowering', 'booster', 'tabs']
  }
];

export const CROP_KITS = [
  {
    id: 'kit-01',
    name: 'IGO Supreme Crop Solution Kit (Fruit & Veg Boost)',
    price: 899,
    mrp: 1350,
    discount: 33,
    description: 'Comprehensive combo specifically designed for high-yielding tomato, chilli, and cucumber gardeners. Includes Premium Hybrid Seeds, NPK Soluble Feed + Bio Organic Seaweed Extract!',
    items: ['prod-seeds-01', 'prod-fert-01', 'prod-bio-01']
  },
  {
    id: 'kit-02',
    name: 'IGO Shield Organic Protection Kit (Disease + Pest Control)',
    price: 999,
    mrp: 1500,
    discount: 33,
    description: 'Zero chemical organic safeguard kit for balcony containers and farms. Includes Katyayani Premium Neem Oil + T-Stanes Trichoderma Biofungicide + Multiplex Bio Fungal Defense Spray!',
    items: ['prod-care-04', 'prod-bio-02', 'prod-gard-04']
  }
];

export const SUBSIDY_INFO = [
  {
    schemeName: 'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)',
    subsidyAmount: 'Up to 55% for small & marginal farmers',
    applicableFor: 'Drip Systems, Sprinkler Systems, Greenhouse structures',
    authorizedProvider: 'IGO Farm Automation',
    processLink: '#'
  },
  {
    schemeName: 'Tamil Nadu Agribusiness Subvention & Machineries Scheme',
    subsidyAmount: '40% to 50% capital subsidy with interest subvention',
    applicableFor: 'Brush Cutters, Sprayers, Earth Augers, Power Weeders',
    authorizedProvider: 'Farmers Factory / STIHL partnered',
    processLink: '#'
  },
  {
    schemeName: 'Govt Organic Farming Promotion Subsidy (Paramparagat Krishi Vikas Yojana)',
    subsidyAmount: '₹31,000 incentive voucher per hectare',
    applicableFor: 'IGO Bio Solutions, Vermicompost, Organic Manures',
    authorizedProvider: 'IGO Bio Solutions',
    processLink: '#'
  }
];

export const SEED_SERVICES: Service[] = [
  {
    id: 'srv-01',
    name: 'Soil Analysis & Laboratory Testing',
    slug: 'soil-analysis-test',
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=600&q=80',
    description: 'Affordable on-site sample collection followed by deep chemical analysis in our Chennai high-tech laboratory. Evaluates NPK, pH levels, carbon indices, and trace minerals.',
    category: 'Expert Services',
    provider: 'IGO Bio Solutions Lab',
    priceQuote: '₹450 / Sample',
    features: [
      '12-parameter nutrition mapping',
      'pH and EC correction advice',
      'Digital report within 48 hours to WhatsApp',
      'Tailored fertilizer and lime suggestions'
    ]
  },
  {
    id: 'srv-02',
    name: 'Custom Drip Irrigation Designing',
    slug: 'drip-irrigation-design',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80',
    description: 'Let our expert fertigation architects design a high-efficiency drip or mist network for your crop fields. Customized layout blueprints optimizing water pressure.',
    category: 'Farm Automation',
    provider: 'IGO Farm Automation',
    priceQuote: 'Free Quote & Blueprint',
    features: [
      'Tailor-made pipe sizing',
      'Nozzle blockage preventative selection',
      'Automation solenoid layout recommendations',
      'Subsidy support document preparation'
    ]
  },
  {
    id: 'srv-03',
    name: 'Smart Drone Spraying Service',
    slug: 'drone-spray-service',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=600&q=80',
    description: 'Fast, automated application of bio-insecticides, organic nutrients, and weed defenses using certified hexacopter drones. Minimizes chemical exposure.',
    category: 'Expert Services',
    provider: 'IGO Drone Services',
    priceQuote: 'From ₹650 / Acre',
    features: [
      '95% water volume reduction',
      'Full field completed in 15 minutes',
      'Zero manual chemical contact',
      'GPS mapped flight plan guarantees 100% covers'
    ]
  },
  {
    id: 'srv-04',
    name: 'Agrarian Property Survey & Estates',
    slug: 'property-survey-estates',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
    description: 'Comprehensive topography mapping, boundary valuation, and agricultural resource evaluation for buyers, lessors, and estates.',
    category: 'Expert Services',
    provider: 'IGO Agri Estates',
    priceQuote: 'On-Site Estimation',
    features: [
      'Sub-meter accuracy GPS boundaries',
      'Farming water-yield assessment',
      'Soil topography elevation contours',
      'Lease valuation consulting'
    ]
  },
  {
    id: 'srv-05',
    name: 'Carbon Credit Registration',
    slug: 'carbon-credit-reg',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
    description: 'Transform your organic sustainable farming practices into yearly recurring cash inflows. We verify your actions and lock carbon points.',
    category: 'Bioproducts',
    provider: 'IGO Bio Solutions',
    priceQuote: 'Consultancy Commission Model',
    features: [
      'Soil carbon content certification',
      'Global offset marketplace listing',
      'Regular yearly incentive payouts',
      'Free organic farming transition blueprints'
    ]
  },
  {
    id: 'srv-06',
    name: 'Polyhouse Structural Erection',
    slug: 'polyhouse-erection',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80',
    description: 'Get an end-to-end greenhouse or polyhouse designed to withstand high winds and Chennai humidity. Automated ventilation systems to prevent fungal spores.',
    category: 'Expert Services',
    provider: 'IGO Greenhouse',
    priceQuote: 'Govt Subsidy Assistance (PMKSY)',
    features: [
      'G.I. pipe framework structural setup',
      '200-micron UV stabilizer cooling film covers',
      'Automated misting and shade nets',
      'Full setup with govt subsidy aid'
    ]
  },
  {
    id: 'srv-07',
    name: 'Precision Fertigation Auditing',
    slug: 'fertigation-audit',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=600&q=80',
    description: 'Our expert agronomists evaluate your current drip lines and liquid fertilizer formulas on-site. Eliminate nutrient washing and mineral crusts.',
    category: 'Expert Services',
    provider: 'IGO Fertigation',
    priceQuote: '₹1,200 / Inspection',
    features: [
      'Nozzle blockage and pressure diagnosis',
      'Water electrical conductivity (EC) tracking',
      'Optimized NPK injection calendar',
      'Secondary nutrients dosage balance'
    ]
  },
  {
    id: 'srv-08',
    name: 'High-Density Orchard Setup',
    slug: 'orchard-setup',
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80',
    description: 'Erect modern high-density mango, guava or citrus orchard plots. Reduces harvest cycle lengths using hybrid clones and optimized spacing models.',
    category: 'Expert Services',
    provider: 'Farmers Factory',
    priceQuote: 'Custom layouts layout',
    features: [
      'Optimum spacing layouts (e.g., 3m x 3m)',
      'Grafted high-yield hybrid saplings',
      '1st-year growth and replacements guarantee',
      'Automated drip plan incorporation'
    ]
  },
  {
    id: 'srv-09',
    name: 'Dairy Farm Automation Consulting',
    slug: 'dairy-automation',
    image: 'https://images.unsplash.com/photo-1527156080170-69f3d6872545?auto=format&fit=crop&w=600&q=80',
    description: 'Modernize traditional dairy cattle houses with automated milking machine units, pasture tags, and silage cutters.',
    category: 'Farm Automation',
    provider: 'IGO Farm Automation',
    priceQuote: 'Interactive plans',
    features: [
      'Milking machine layout spacing',
      'Cattle health and rumination sensor tags',
      'SILO fodder chopper setups',
      'Hygienic waste gasifier designs'
    ]
  },
  {
    id: 'srv-10',
    name: 'Cold Storage Logistical Liaison',
    slug: 'cold-storage-logistics',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    description: 'Ship high-value perishables, seafood or exotic fruits from Chennai to global international gateways with complete temperature traceability.',
    category: 'Expert Services',
    provider: 'IGO Exports & Imports',
    priceQuote: 'Per Kg Logistics quotation',
    features: [
      'Continuous battery-tracked reefer vehicles',
      'Port custom clearances paperwork',
      'Phytosanitary certification support',
      'Direct Chennai Port cold room bookings'
    ]
  },
  {
    id: 'srv-11',
    name: 'Agrarian Legal Consulting',
    slug: 'agri-legal-consulting',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
    description: 'Ensure smooth land records conversion, farm leases, or legal titles validation in Chennai and Tamil Nadu districts.',
    category: 'Expert Services',
    provider: 'IGO Group of Companies',
    priceQuote: '₹1,500 Consultation',
    features: [
      'Pattah, Chitta, Adangal validation',
      'Custom agricultural lease templates',
      'Land revenue tax registrations helpline',
      'Government land classification reviews'
    ]
  }
];

export const SEED_COURSES: Course[] = [
  {
    id: 'cls-01',
    title: 'Precision Hydroponic Masterclass',
    slug: 'precision-hydroponics',
    image: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80',
    instructor: 'Dr. S. Anbarasan',
    lessonsCount: 18,
    duration: '6 Hours',
    level: 'Intermediate',
    originalPrice: 2999,
    currentPrice: 1499,
    description: 'Step-by-step masterclass on soil-less tomato & lettuce cultivation. Includes water quality, nutrient chemistry formulas, EC/pH parameters, and design of home or commercial deep-water channels as well as NFT setups.',
    modules: [
      'Introduction to Soil-less Cultivation',
      'Water parameters & Filtration requirements',
      'NPK Liquid Chemistry Formulation guides',
      'TDS, EC, and pH balancing schedules',
      'NFT vs Deep Water Culture physical setups',
      'Pest protection inside hydroponic greenhouses'
    ]
  },
  {
    id: 'cls-02',
    title: 'Organic Farming & Biofertilizers',
    slug: 'organic-farming-biofertilizers',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    instructor: 'Murugan G. (Organic Pioneer)',
    lessonsCount: 12,
    duration: '4 Hours',
    level: 'Beginner',
    originalPrice: 1249,
    currentPrice: 499,
    description: 'A complete practical curriculum covering organic agriculture. Discover secrets of Panchagavya, Jeevamirtham, Trichoderma Viride inoculum, vermirouting, and hot compost mixtures.',
    modules: [
      'Understanding Soil Ecosystems',
      'Panchagavya & Jeevamirtham formulation',
      'Fungal antagonists: Trichoderma viride application',
      'Designing compost stations and worm bins',
      'Organic companion planting secrets',
      'Eco-friendly pest defense with neem fractions'
    ]
  },
  {
    id: 'cls-03',
    title: 'DGCA Certified Agri Drone Pilot Training',
    slug: 'agri-drone-pilot',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=600&q=80',
    instructor: 'Capt. Hari Prasath',
    lessonsCount: 24,
    duration: '12 Hours',
    level: 'Professional',
    originalPrice: 9999,
    currentPrice: 4999,
    description: 'Learn dynamic drone controls for agrochemical deployment, infrared crop disease inspection, and precise volumetric crop count calculations.',
    modules: [
      'Basic Aerodynamics & Multi-rotor physics',
      'DGCA Rules and airspace permissions',
      'Autonomous flight planning & GPS routes',
      'Nozzle calibration & aerosol control',
      'Infrared Multispectral Crop Disease analysis',
      'Emergency recovery commands in high winds'
    ]
  }
];

export const SEED_POSTS: BlogPost[] = [
  {
    id: 'post-01',
    title: 'Maximizing Paddy Yields in Cauvery Delta',
    slug: 'maximize-paddy-cauvery',
    excerpt: 'Actionable techniques to double rice produce using bio-boosters, wet-dry water cycles, and organic nitrogen formulas.',
    content: 'Paddy farming in the Cauvery Delta region faces multiple constraints - from erratic water supplies to escalating fertilizer costs. Fortunately, the System of Rice Intensification (SRI) provides an efficient path. By transplanting young seedlings early (8-12 days) rather than later, spacing them widely, and maintaining moist soils instead of continuous flooding, farmers can double their harvest while reducing water needs by 40%. Additionally, integrating Azospirillum and Phosphobacteria bio-inputs helps fix atmospheric nitrogen natively, saving up to 25% on chemical urea. Explore IGO Bio Solutions for tailored microbial cultures designed for Tamil Nadu soil conditions.',
    category: 'Crop Advice',
    author: 'Dr. Radha Krishnan (Agronomy Consultant)',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
    createdAt: '2026-05-18T10:00:00Z',
    tags: ['Paddy', 'Biofertilizers', 'Cauvery Delta', 'SRI']
  },
  {
    id: 'post-02',
    title: 'The Ultimate Guide to Soil Enrichment using Vermicompost',
    slug: 'guide-vermicompost-soil',
    excerpt: 'Restore depleted organic matter, establish soil structure and nourish beneficial microbes using digested worm castings.',
    content: 'Years of heavy synthetic fertilizer applications have depleted organic soil carbon from an optimal 1.5% down to under 0.4% in many districts. Organic Vermicompost acts as the fastest rescue mechanism. Comprising red-worm digested plant matter, it is rich in humic acids, growth-promoting hormones, and a highly active microbiome. Adding vermicompost improves soil moisture holding capacity, makes phosphate minerals soluble, and buffers soils against root diseases. For garden potting soils, mix 30% Farmers Factory Vermicompost with cocopeat and red soil for exceptional results.',
    category: 'Soil Health',
    author: 'Rajesh Kumar (Organic Farmer)',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80',
    createdAt: '2026-05-25T11:00:00Z',
    tags: ['Vermicompost', 'Soil Enrichment', 'Organic', 'Manures']
  },
  {
    id: 'post-03',
    title: 'Smart Drip Automation: Reducing Water Usage by 60%',
    slug: 'smart-drip-irrigation-saving',
    excerpt: 'How IoT sensors, automated mist solenoid valves, and gravity drip lines prevent water waste while multiplying fertilizer efficiency.',
    content: 'Traditional flood irrigation wastes up to 70% of applied water via evapo-transpiration and deep percolation. Moreover, it carries expensive dissolved fertilizers away from active root clusters. Drip irrigation coupled with low-cost automation resolves this problem. By placing emitters precisely beside each crop root and leveraging smart soil-moisture probes, the system triggers short, precise watering intervals only when soil drying occurs. This preserves root aeration and maintains optimal nutrient humidity, resulting in up to 40% higher crop yield. Contact IGO Farm Automation to receive a customized schematic design tailored for your horticultural estate.',
    category: 'Farm Tech',
    author: 'Anita Devendra (Agribusiness Engineer)',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80',
    createdAt: '2026-06-01T09:00:00Z',
    tags: ['Drip Systems', 'IoT Sensors', 'Automation', 'Conservation']
  }
];
